### ISSUE TITLE
homebridge startet nicht

### ISSUE THREAD

**Issue by Tho75** [thkl/homebridge-homematic#108]
Hallo zusammen,
ich habe das Problem das "homebridge" nich startet.

Wenn ich es richtig verstehe gibt es ein Problem beim Laden der Homematic devices?!
Hat jemand einen Tip für mich?

Hier das Log:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-04-30 18:09:31] Loaded plugin: homebridge-homematic
[2017-04-30 18:09:31] Registering platform 'homebridge-homematic.HomeMatic'
[2017-04-30 18:09:31] ---
[2017-04-30 18:09:31] Loaded config.json with 1 accessories and 1 platforms.
[2017-04-30 18:09:31] ---
[2017-04-30 18:09:31] Loading 1 platforms...
[2017-04-30 18:09:31] [homematic-ccu2] Initializing HomeMatic platform...
[2017-04-30 18:09:31] [homematic-ccu2] Homematic Plugin Version 0.0.70
[2017-04-30 18:09:31] [homematic-ccu2] Plugin by thkl  https://github.com/thkl
[2017-04-30 18:09:31] [homematic-ccu2] Homematic is a registered trademark of the EQ-3 AG
[2017-04-30 18:09:31] [homematic-ccu2] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[2017-04-30 18:09:31] [homematic-ccu2] init RPC for 0
[2017-04-30 18:09:31] [homematic-ccu2] Fetching Homematic devices...
[2017-04-30 18:09:31] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by thkl** [comment]
Das schaut mir nach einer kaputten config.json aus. Bitte mal schauen ob die Eintragungen in accessories richtig sind. Das ist kein homematic - plugin Thema

**Comment by LSchuetzi84** [comment]
Ich habe das gleiche Problem. Die config.json ist: 
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"accessories": [{

}],

"platforms": [{
"platform": "HomeMatic",
"name": "HomeMatic CCU2",
"ccu_ip": "192.168.2.105",
"filter_device": [],
"filter_channel": [],
"outlets": [],
"doors": [],
"programs": [],
"subsection": "HomeKit"
}]
}

erhalte die gleiche Fehlermeldung:
[5/9/2017, 8:36:12 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
