### ISSUE TITLE
Homebridge startet nicht mit Homematic Plugin

### ISSUE THREAD

**Issue by LSchuetzi84** [thkl/homebridge-homematic#112]
Ich habe das gleiche Problem wie man anderer hier. 
Wenn ich die config.json ohne homematic Inhalt ausführe, funktioniert sie und ich kann mich connecten. Wenn ich aber, wie unten, meine CCU2 hinzufüge dann erhalte ich folgenden Fehler. 

Die config.json ist:
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"accessories": [{

}],

"platforms": [{
"platform": "HomeMatic",
"name": "HomeMatic CCU2",
"ccu_ip": "192.168.2.105",
"filter_device": [],
"filter_channel": [],
"outlets": [],
"doors": [],
"programs": [],
"subsection": "HomeKit"
}]
}

**ich erhalte die Fehlermeldung:**
[5/9/2017, 8:36:12 PM] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:50
if (name.indexOf('.') == -1) {
^

TypeError: Cannot read property 'indexOf' of undefined

**Comment by LSchuetzi84** [comment]
siehe auch #108 
Dort habe ich zuerst nachgelesen, jedoch konnte ich keine Lösung finden.

**Comment by jp112sdl** [comment]
Hast du es mal versucht, die (leere) "accessories"-Sektion komplett weg zu lassen?

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"platforms": [{
"platform": "HomeMatic",
"name": "HomeMatic CCU2",
"ccu_ip": "192.168.2.105",
"filter_device": [],
"filter_channel": [],
"outlets": [],
"doors": [],
"programs": [],
"subsection": "HomeKit"
}]
}

**Comment by jp112sdl** [comment]
...oder wenn das nicht geht, dann mal die {} weglassen?

{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},

"accessories": [],

"platforms": [{
"platform": "HomeMatic",
"name": "HomeMatic CCU2",
"ccu_ip": "192.168.2.105",
"filter_device": [],
"filter_channel": [],
"outlets": [],
"doors": [],
"programs": [],
"subsection": "HomeKit"
}]
}

**Comment by bprskalo** [comment]
grundsätzlich sieht deine config gut aus

ich habe mir erlaubt diese mal zu strukturieren .. liest sich so halt einfacher :-)

du kannst das file nehmen und von.txt auf .json umbenennen 

ist den die ip adresse der ccu2 die 2.105 ?

[config.txt](https://github.com/thkl/homebridge-homematic/files/991932/config.txt)

**Comment by LSchuetzi84** [comment]
Vielen Dank für eure schnelle Hilfe!
Ich habe den Code von bprskalpo verwendet und nun scheint der Fehler verschwunden. Im Code wurde der Abschnitt accessories weggelassen. 
Jetzt läuft das script jedoch in einen neuen Fehler: 

[2017-05-11 08:38:51] [HomeMatic CCU2] Initializing HomeMatic platform...
[2017-05-11 08:38:51] [HomeMatic CCU2] Homematic Plugin Version 0.0.72
[2017-05-11 08:38:51] [HomeMatic CCU2] Plugin by thkl  https://github.com/thkl
[2017-05-11 08:38:51] [HomeMatic CCU2] Homematic is a registered trademark of the EQ-3 AG
[2017-05-11 08:38:51] [HomeMatic CCU2] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[2017-05-11 08:38:51] [HomeMatic CCU2] will connect to your ccu at 192.168.2.105
[2017-05-11 08:38:51] [HomeMatic CCU2] init RPC for BidCos-RF.
[2017-05-11 08:38:51] [HomeMatic CCU2] Fetching Homematic devices...
[2017-05-11 08:38:51] [Homebridge Server] is listening on: http://192.168.2.115:8765
[2017-05-11 08:38:51] [HomeMatic CCU2] XML-RPC server for interface BidCos-RF. is listening on port 9090.
[2017-05-11 08:38:51] [HomeMatic CCU2] Creating Local HTTP Client for CCU RPC Events
/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/protocol.js:28
        var content = Buffer.alloc(0);
                             ^

TypeError: Buffer.alloc is not a function
    at Object.Protocol.encodeRequest (/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/protocol.js:28:30)
    at methodCall (/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:168:35)
    at HomeMaticRPC.connect (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:226:17)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:147:10
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:277:39)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1523:8)
    at nextTickCallbackWith1Arg (node.js:426:9)
    at process._tickCallback (node.js:348:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3



Gibt es irgendwelche Konfigurationen oder Erweiterungen, die an der CCU2 installiert werden müssen? 
Auf meiner CCU2 sind der CUX-Daemon sowie die XML-API installiert. 

Als zusätzliches Gewerk habe ich "HomeKit" angelegt.

**Comment by bprskalo** [comment]
was mir auffällt ist das bei dir über den port 8075 kommuniziert wird ..  dieser sollte eigentlich 9090 sein 

hast du da einen wert in deiner config ?

**Comment by bprskalo** [comment]
siehe auch im read.me

"Ports: the plugin will use local Port 9090 to communicate with the ccu rfd daemon. Port 9091 for wired and 9092 for hmip (if they are in use). If these ports are in use by other applications, you can change them by the following key in your config.json

"local_port":8080"

**Comment by LSchuetzi84** [comment]
Das ist nur der Homematic-Server, welche eine Weboberfläche bereitstellt. Dieser hört auf den Port 8765.

**Comment by LSchuetzi84** [comment]
Ok Fehler gefunden. Es lag an einer veralteten node.js version. Habe diese aktualisiert und nun läuft es. 
Vielen Dank für eure Hilfe!!

**Comment by thkl** [comment]
Nachtrag:

Ja, ich habe das xmlrpc Modul durch das aktuelle binrpc Modul von @hobbyquaker ersetzt. Das macht die Kommunikation zwischen der CCU und dem Plugin schneller bzw. braucht weniger Traffic.  

Damit wird aber eine Node Version >=4.5 benötigt.  
Der npm Updater wirft allerdings eine Warnung wenn die installierte Version nicht passt.
