### ISSUE TITLE
Update von 0.0.70 auf 0.0.73 werden keine Geräte mehr ausgelesen

### ISSUE THREAD

**Issue by markoox** [thkl/homebridge-homematic#115]
Hallo, nach dem Update von 0.0.70 auf die 0.0.73, werden keine Geräte mehr aus der Homematic ausgelesen und ich kann diese auch nicht mehr steuern. Wenn ich wieder zurück auf die 0.0.70 gehe, dann geht wieder alles.

An was kann denn das liegen?

Schon mal besten Dank für eine Info.

**Comment by markoox** [comment]
TypeError: Buffer.alloc is not a function
    at Object.Protocol.encodeRequest (/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/protocol.js:28:30)
    at methodCall (/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:168:35)
    at HomeMaticRPC.connect (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:235:17)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:155:10
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:286:39)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1523:8)
    at nextTickCallbackWith1Arg (node.js:426:9)
    at process._tickCallback (node.js:348:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3

**Comment by markoox** [comment]
hier die Meldung die ich bekomme

**Comment by bprskalo** [comment]
das sieht nach dem "berüchtigten" node.js fehler aus .. du musst mindestens auf der version 4.5 sein .. siehe dazu die #108 oder die #109 oder die #111

**Comment by thkl** [comment]
Richtig ! 
npm update meckert auch wenn node zu klein ist. ich schau mal ob ich bei node < 4.5 das xmprpc statt rpcbin nehme. Ich muss ja für HmIP auch auf das zurückfallen.

**Comment by markoox** [comment]
Hallo zusammen, wenn ich npm update eingebe, oder sudo npm upgrade -g homebridge wird kein Update installiert. So müsste ich doch auf der aktuellen Version sein, oder nicht? Denn bei mir geht es mit 0.0.73 immer noch nicht. 

wWeis noch jemand einen Rat?

Gruß

Marko

**Comment by thkl** [comment]
jaja aber node.js muss aktualisiert werden. Mindestens Version 4.5 dann ist der Fehler weg.

**Comment by markoox** [comment]
wie mache ich das?

Gruß

Marko Ochs

**Comment by thkl** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=19&t=27465&p=364184#p364184

**Comment by markoox** [comment]
Super, besten Dank. Jetzt klappt es auch bei mir mit der 0.0.73.

Wünsche noch einen schönen Abend.

Gruß

Marko

**Comment by markoox** [comment]
Hallo zusammen,
ich glaube ich brauche doch noch mal eure Hilfe. Denn nach dem Neustart der Homebridge, geht es mit der 0.0.73 wieder nicht. Erst wenn ich wieder auf die 0.0.70 zurück gehen. Auch die Zwischen Versionen habe ich mal getestet, 0.0.71 bis 0.0.73, zeigen gleiches Verhalten.


hier mal das was er anzeigt beim Update auf die aktuellste Version:

pi@raspberrypi:~ $ npm install npm@latest -g
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└── npm@4.6.1

npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-05-24T07_53_08_234Z-debug.log


Gruß

Marko

**Comment by thkl** [comment]
Das muss als Root ausgeführt werden.  Also ggf mit sudo davor

**Comment by markoox** [comment]
oh man,

manchmal ist man blind. Danke.

jetzt sah es beim Update so aus:

pi@raspberrypi:~ $ sudo npm install npm@latest -g
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/lib
└── npm@4.6.1

pi@raspberrypi:~ $ sudo npm install -g homebridge-homematic@0.0.73
/usr/local/lib
└─┬ homebridge-homematic@0.0.73
  └─┬ binrpc@3.1.0
    ├─┬ binary@0.3.0
    │ ├── buffers@0.1.1
    │ └─┬ chainsaw@0.1.0
    │   └── traverse@0.3.9
    └── put@0.0.6

wenn ich dann die Homebridge starte liest er auch alle homematic Geräte wieder ein unter der 0.0.73.

Es kommt aber noch diese Meldung:

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:509:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at NetatmoPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/index.js:56:7)
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:3679:13
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:997:17)
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:847:20
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:3676:17
    at /usr/local/lib/node_modules/homebridge-netatmo/node_modules/async/dist/async.js:339:31
    at /usr/local/lib/node_modules/homebridge-netatmo/index.js:71:13
    at CameraDeviceType.buildAccessories (/usr/local/lib/node_modules/homebridge-netatmo/lib/netatmo-device.js:114:5)
    at CameraDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/lib/netatmo-device.js:55:14)
    at CameraDeviceType.<anonymous> (/usr/local/lib/node_modules/homebridge-netatmo/lib/netatmo-device.js:69:13)

ist das Ok so?

Gruß

Marko

**Comment by thkl** [comment]
Bridge läuft bereits.

**Comment by jp112sdl** [comment]
Da läuft schon ein homebridge-Prozess.
Starte am besten mal deine Kiste neu...

**Comment by markoox** [comment]
Ich habe die Kiste durchgestartet, jetzt geht die 0.0.73 wieder nicht. Was ist denn das nur?
Wenn ich gleich nach dem Update sudo npm install npm@latest -g die 0.0.73 installiere und mit dem Befehl Homebridge Starte, dann läuft alles. Starte ich dann den Raspberry neu, geht das Homematic Modul nicht mehr.

Gruß

Marko
