### ISSUE TITLE
Config example

### ISSUE THREAD

**Issue by Samfox2** [thkl/homebridge-homematic#12]
Hi Thomas,

I got my ccu2 today and wanted to add it to my running homebridge.
I have a few "Funk-Heizkörperthermostate" (HM-CC-RT-DN) and a " Funk- Tür und Fensterkontakt" (HM-Sec-SC-2). Your plugin is installed but I am struggling with my config.json.
I really don`t get it how to get it running, e.g. which config point means what?
What do need to configure to find my accessories?
Could you please explain it a bit further to me?

if I add the platform to my config.json I get the following error message:

[HomeMatic CCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
[HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[HomeMatic CCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
[HomeMatic CCU] Fetching Homematic devices...
Loading 0 accessories...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by Samfox2** [comment]
Ok, one step more...
I had to add the key local_port, as the default port 9090 is actually used by another process.

Now my devices are found, but I get another error:

```
[HomeMatic CCU] Method call params for 'system.listMethods': homebridge
[HomeMatic CCU] Method listDevices does not exist
[HomeMatic CCU] Method newDevices does not exist
[HomeMatic CCU] Initializing platform accessory 'HM-CC-RT-DN LEQxxxxxx:4'...
[HomeMatic CCU] Initializing platform accessory 'HM-CC-RT-DN LEQxxxxxx:4'...
[HomeMatic CCU] Initializing platform accessory 'HM-CC-RT-DN LEQxxxxxx:4'...
[HomeMatic CCU] Initializing platform accessory 'HM-Sec-SC-2 LEQxxxxxx:1'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ââââââââââââââ
    â xxx-xx-xxx â
    ââââââââââââââ

Homebridge is running on port 55826.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:132:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:347:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:50:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:220:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
```

My config looks like the following:
```
    "platforms": [
       {
           "platform": "HomeMatic",
           "name": "HomeMatic CCU",
           "ccu_ip": "192.168.x.xxx",
           "local_port": "55826",
           "filter_device":[],
           "filter_channel":[],
           "outlets":[],
           "doors":[],
           "programs":[]
        }
    ],
```

any ideas?

**Comment by Samfox2** [comment]
It's working now, only had to change the port as it was already in se by homebridge.
