### ISSUE TITLE
This callback function has already been called by someone else; it can only be called one time

### ISSUE THREAD

**Issue by Sillium** [thkl/homebridge-homematic#131]
Homebridge läuft im Docker Container bei mir. Alles läuft im Prinzip reibungslos. Sobald ich das homebridge-homematic Plugin zusätzlich installiere, wird zuverlässig reproduzierbar folgende Logmeldung produziert und Homebridge crasht. Kennt jemand dieses Problem?

```
homebridge    | /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
homebridge    |       throw new Error("This callback function has already been called by someone else; it can only be called one time.");
homebridge    |       ^
homebridge    |
homebridge    | Error: This callback function has already been called by someone else; it can only be called one time.
homebridge    |     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
homebridge    |     at HomeMaticRegaRequest.script.e (/usr/lib/node_modules/homebridge-homematic/index.js:297:4)
homebridge    |     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:41:9)
homebridge    |     at emitNone (events.js:91:20)
homebridge    |     at IncomingMessage.emit (events.js:185:7)
homebridge    |     at endReadableNT (_stream_readable.js:974:12)
homebridge    |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
homebridge    |     at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by thkl** [comment]
Sollte ab 0.0.80 erledigt sein.
