### ISSUE TITLE
 fvalue is not defined

### ISSUE THREAD

**Issue by derkopp** [thkl/homebridge-homematic#149]
Since updating to 82 I receive the following message and Homebridge crashes (no change to config.json or new accessories).

```
[2017-09-27 13:43:23] [HomeMatic CCU] NPM 0.0.82 vs Local 0.0.82
/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorServiceIP.js:34
		         callback(null,fvalue/10)
		                       ^

ReferenceError: fvalue is not defined
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorServiceIP.js:34:26
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:123:32
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:234:9
    at /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:217:9
    at Deserializer.callback (/usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:42:7)
    at Deserializer.onDone (/usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at emitNone (events.js:86:13)
    at SAXStream.emit (events.js:185:7)
    at Object.SAXStream._parser.onend (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)

```

**Comment by thkl** [comment]
ok .. thats a typo bug. If you want to fix it for the moment by yourself:
edit the file  /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorServiceIP.js

goto line number 34:

change 
` callback(null,fvalue/10)`

into 

` callback(null,value/10)`

**Comment by iuliusmaximilian** [comment]
@thkl Can you please commit the change to the repository
