### ISSUE TITLE
Fehler beim Ausführen

### ISSUE THREAD

**Issue by Seehofweg** [thkl/homebridge-homematic#173]
Ich habe alles nach der Anleitung [https://wiki.fhem.de/wiki/Homebridge_einrichten](https://wiki.fhem.de/wiki/Homebridge_einrichten) installiert. Wenn ich homebridge starte, kommt diese Fehlermeldung:

`Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:384
  var encodedPayload = (buffer.readUInt32BE(4) + (buffer.readUInt32BE(0) * Math.pow(2, 32))).toString(36).toUpperCase().padStart(9, '0');
                                                                                                                        ^

TypeError: (buffer.readUInt32BE(...) + (buffer.readUInt32BE(...) * Math.pow(...))).toString(...).toUpperCase(...).padStart is not a function
    at Bridge.Accessory.setupURI (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:384:121)
    at Server._printSetupInfo (/usr/lib/node_modules/homebridge/lib/server.js:600:32)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:8)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:381:14)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at regarequest.script.e (/usr/lib/node_modules/homebridge-homematic/index.js:300:4)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
`

**Comment by thkl** [comment]
Ich würde mal meinen, hier muss node aktualisiert werden.
