### ISSUE TITLE
Noch keine Unterstützung für Strom-/Gaszähler HM-ES-TX-WM

### ISSUE THREAD

**Issue by mdietrich** [thkl/homebridge-homematic#175]
Das Gerät tauch als Typ HM-ES-TX-WM:POWERMETER_IGL in den Logs auf. Ich schätze es wird eine angepasste Service-Klasse benötigt

**Comment by pbksol** [comment]
HomeKit hat generell keinen Support für Zähler. Die Liste der aktuell unterstützten Geräte findet sich hier: https://user-images.githubusercontent.com/884355/30632936-1b38c5d4-9dea-11e7-8113-917768d2a1e9.png – da hatte thkl ein entsprechendes Bild gepostet.

**Comment by thkl** [comment]
Gaszähler gibt es soweit ich weiss keine Characteristics .. Powermeter kommt mit dem nächsten Update. (geht nur in Eve - denn dort wird der passende Service ausgewertet / Home App ignoriert das ganze)

**Comment by CM-UH** [comment]
Hallo Thomas,
ich habe versucht meinen Stromzähler in Homebridge zu integrieren.
Wenn ich den "Powermeter IGL" in der "Channel_Config" zufüge startet die Homebridge nicht mehr.
Im Log kommt
> [2020-1-9 19:25:47] [HomeMatic CCU3] if PONG is PONG CCU is alive
[2020-1-9 19:25:49] TypeError: Service.PowerMeterService is not a constructor
    at HomeMaticHomeKitEnergyCounterService.createDeviceService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitEnergy                        CounterService.js:23:16)
    at HomeMaticHomeKitEnergyCounterService.HomeKitGenericService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericServic                        e.js:69:8)
    at new HomeMaticHomeKitEnergyCounterService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitEnergyCounterService.j                        s:8:47)
    at HomeMaticChannelLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:340:22
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:300:21
    at Array.map (<anonymous>)
    at HomeMaticPlatform.buildaccesories (/usr/local/lib/node_modules/homebridge-homematic/index.js:288:16)
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:234:9
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1161:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Kannst du mir bitte helfen, ich finde den Fehler einfach nicht :-(
