### ISSUE TITLE
HomeMaticHomeKitMotionDetectorServiceIP.js

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#193]
Hallo zusammen, ich habe gerade den Homematic IP Bewegungsmelder HmIP-SMO eingebunden aber die Homebridge schmeisst folgende Fehlermeldung bei Starten. Hat Jemand eine Idee was ich tun kann?

```
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorServiceIP.js:34
		         callback(null,fvalue/10)
		                       ^

ReferenceError: fvalue is not defined
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorServiceIP.js:34:26
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:141:32
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:252:9
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:217:9
    at Deserializer.callback (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:42:7)
    at Deserializer.onDone (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at emitNone (events.js:86:13)
    at SAXStream.emit (events.js:188:7)
    at SAXParser.SAXStream._parser.onend (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)

```

**Comment by iuliusmaximilian** [comment]
Habe die Lösung gefunden: https://github.com/thkl/homebridge-homematic/issues/149
