### ISSUE TITLE
CuXD-Schaltkanäle Exception

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#2]
Ich habe ein paar CUXd-Schaltkanäle die jetzt als "Nicht verfügbar" angezeigt werden und beim Versuch zu ändern wirft es im Log folgende Exception:

[HomeMatic CCU2] Send true to Datapoint STATE at CUxD.CUX0200004:1
/usr/local/lib/node_modules/homebridge-homematic/index.js:190
      var rega = new RegaRequest(this.log, this.ccuIP);
                     ^
ReferenceError: RegaRequest is not defined
    at HomeMaticPlatform.setValue (/usr/local/lib/node_modules/homebridge-homematic/index.js:190:22)
    at Object.HomeMaticGenericChannel.command (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannel.js:585:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannel.js:68:12)
    at emit (events.js:118:17)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:152:10)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:516:22)
    at HAPServer.emit (events.js:118:17)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:682:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:172:39)
    at IncomingMessage.emit (events.js:104:17)

**Comment by thkl** [comment]
oops .  fixed in 0.0.7

**Comment by Apollon77** [comment]
Sie werden jetzt initial immer noch als "n.v."in der EVE App angezeigt und erst nach einmaligem Schalten ist der Status dann EIN/AUS ...

**Comment by thkl** [comment]
Was ist das für ein Kanaltyp ? Switch ?

**Comment by Apollon77** [comment]
Ja

**Comment by thkl** [comment]
ok mal 0.0.8 probieren ...

**Comment by thkl** [comment]
0.0.10 ändert noch mal das Timing crasht nicht wenn Callbacks Pointer fehlen

**Comment by Apollon77** [comment]
0.0.10  worx :-)

**Comment by Apollon77** [comment]
korrektur ... 0.0.11 ist mir aufgefallen das der Status falsch ist. Es wird aktuell "EIN" in Eve angezeigt obwohl in der CCU "AUS" steht. Irgendwas ist da schieff
