### ISSUE TITLE
Raspberrymatic - Homebridge

### ISSUE THREAD

**Issue by Hifclif** [thkl/homebridge-homematic#216]
Hi, mein versuch auf den RasperryMatic zu wechseln scheint nix zu sein. Ist da was anders als bei der CCU2?

2018-3-15 17:45:38] [RaspberryMatic ] get CurrentPosition
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for 001357099600CA:4 LEVEL
[2018-3-15 17:45:38] [RaspberryMatic ] get TargetPosition
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for 001357099600CA:4 LEVEL
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for 00109709A8EF90:1 STATE
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for OEQ0015623:1 STATE
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue (OEQ0015623:1 STATE) Response undefined Errors: Error: This socket is closed
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for 0008D8A989EF30:4 LEVEL
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for 0008D8A989EF30:4 LEVEL
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for 0008570991049D:4 STATE
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for 00109709AAA9CD:1 STATE
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue Call for NEQ1680006:1 STATE
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue (NEQ1680006:1 STATE) Response undefined Errors: Error: This socket is closed
[2018-3-15 17:45:38] [RaspberryMatic ] RPC getValue (OEQ0119192:1 STATE) Response undefined Errors: Error: This socket is closed
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitKeymaticService.js:29:25
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:141:32
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:252:9
    at /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:217:9
    at Object.callback (/usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:173:25)
    at /usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:149:29
    at process._tickCallback (internal/process/next_tick.js:114:19)

Die Kommunikation scheint geblockt zu sein?
sg

**Comment by nicoh88** [comment]
Benutze auch RaspberryMatic bzw. [piVCCU](https://github.com/alexreinert/piVCCU) in Verbindung mit Homebridge.

**Denkanstoß:** IP korrekt? Homematic Firewall eingeschränkt? Reboot?

**Comment by thkl** [comment]
Auch wenn ich die Ursache nicht lösen kann, würde ich mal dafür sorgen, das es nicht crasht, wenn der RPC Socket geschlossen ist. 

Es gibt einen Watchdog, der die Schnittstelle reinitialisiert, wenn über einen gewissen Zeitraum keine Daten kommen. Den werde ich dazu missbrauchen, die Verbindung wieder aufzubauen.

**Comment by Hifclif** [comment]
Habe in neu installiert, Konfig aus der CCU2 exportiert / importiert. IP ist gleich, starte Homebridge die ladet die Module und beim Homatic stellt es ihn auf.

**Comment by thkl** [comment]
ich bau das nachher mal um, das das nicht mehr Crasht, aber das wird nicht das Socket close lösen ...

**Comment by Hifclif** [comment]
OK. Ist das ein Thema von dem RaspberryMatic. Denn die CCU2 läuft ja ohne Problem.

**Comment by nicoh88** [comment]
Steht XML RPC auf Vollzugriff?
IP-Adressbereich unten dabei?

![87053670-7a94-4587-8d34-3efb0182ea8e](https://user-images.githubusercontent.com/264264/37509731-d189b6b0-28f8-11e8-9893-cd7f6a56dd56.jpeg)

**Comment by Hifclif** [comment]
XML-RPC war schon auf Vollzugriff. Remote API habe ich auch auf Vollzugriff gestellt (unabhängig auch die IP eingetragen).

**Comment by nicoh88** [comment]
Hmm, dann habe ich leider keine Idee mehr.

**Comment by Hifclif** [comment]
Wenn ich die "subsection" - homkit (mein Gewerk) rausnehme schmiert es nicht ab.

**Comment by nicoh88** [comment]
Gibt es das Gewerk "homkit" eventuell nicht in deiner Homematic WebUI nicht? Eventuell ein Schreibfehler?

**Comment by Hifclif** [comment]
Ich habe das Gewerk Homekit und auch in der Konfig genau so geschrieben. Da auch die Konfig vom CCU2 übernommen ist ist alles gleich bis auf den Unterbau mit dem RaspberryMatic.

**Comment by thkl** [comment]
Der Crash ist im Keymatic Modul aufgetreten. Dort hab ich was eingebaut, das das nicht mehr passieren sollte.  Nur löst das das Problem nicht.  

BTW: ich habe vorhin das Produktivsystem auf die aktuelle Version gehoben. Das redet mit einer Raspberrymatic (allerdings Version 2.29.22; ich bin zu faul für den Updateprozess :))

**Comment by nicoh88** [comment]
Hmm, bei mir keine Probleme mit RaspberryMatic / piVCCU 2.31.25

**Comment by Hifclif** [comment]
Also habe es vorher nochmals getestet mit der Version.103 und ist ebenfalls abgeraucht.
Gewerk ist da:
![grafik](https://user-images.githubusercontent.com/35782387/37566935-07b7e072-2ac0-11e8-9e3e-85ffa60a534c.png)

**Comment by thkl** [comment]
Welche Raspberrymatic Version ist das denn die crasht ?

**Comment by Hifclif** [comment]
Die aktuellste: https://github.com/jens-maus/RaspberryMatic/releases/download/2.31.25.20180225/RaspberryMatic-2.31.25.20180225-rpi3.zip
 Gerade nochmals getestet:
[2018-3-18 15:32:08] [Homematic-CCU2] RPC getValue Call for 0008D8A989EF30:4 LEVEL
[2018-3-18 15:32:08] [Homematic-CCU2] RPC getValue Call for 0008D8A989EF30:4 LEVEL
[2018-3-18 15:32:08] [Homematic-CCU2] RPC getValue Call for 00109709AAA9CD:1 STATE
[2018-3-18 15:32:08] [Homematic-CCU2] RPC getValue Call for OEQ1318387:1 STATE
[2018-3-18 15:32:08] [Homematic-CCU2] RPC getValue (OEQ1318387:1 STATE) Response undefined Errors: Error: This socket is closed
[2018-3-18 15:32:08] [Homematic-CCU2] RPC getValue Call for 00109709AAA9C5:1 STATE
[2018-3-18 15:32:08] [Homematic-CCU2] RPC getValue (OEQ1318387:1 STATE) Response undefined Errors: Error: This socket is closed
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitContactService.js:118:8
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:155:34
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:325:9
    at /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:236:7
    at Object.callback (/usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:173:25)
    at /usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:149:29
    at process._tickCallback (internal/process/next_tick.js:114:19)
root@homekit-server:~#

**Comment by Hifclif** [comment]
Version: 
[2018-3-18 15:32:05] [Homematic-CCU2] NPM 0.0.103 vs Local 0.0.103

**Comment by thkl** [comment]
Ok ich bau mir mal so eine RM ...

**Comment by thkl** [comment]
Hm mich hab jetzt mal eine RM leer installiert. Keine Backups eingespielt nix .. ein IP Gerät und einen BidCos-RF Schaltaktor angelernt. Da crasht nix ...  🧐

**Comment by Hifclif** [comment]
Kann es sein das es von den 
 "type": "HmIP-BBL:BLIND_VIRTUAL_RECEIVER",
            "service": "HomeMaticHomeKitBlindServiceIP"
kommt?

**Comment by thkl** [comment]
Nein oben der Fehler kommt aus HomeMaticHomeKitContactService von passierte bei der Abfrage von   OEQ1318387 ... Der Erste Fehler bei Dir kam aus der Keymatic .. es tritt also aktuell nur an der RF Schnittstelle auf

**Comment by Hifclif** [comment]
Zum Setup muss ich noch sagen verwende ich den HmIP-RFUSB.

**Comment by Hifclif** [comment]
Hi, Zusammen, auf: https://github.com/jens-maus/RaspberryMatic ist jetzt beschrieben das HomeMaticIP only:  USB Stick – HmIP-RFUSB
Denke das kommt gut hin zu meinem Problem? Bisher war das so nicht beschrieben.
cu

**Comment by Hifclif** [comment]
Hier kurz ein Info. Habe das neue Modul von ELV für den RPi und mit dem geht alles wie es soll. Liegt also an dem USB-FunkDings.
Schöne Grüße
