### ISSUE TITLE
HomeMaticHomeKitBlindServiceIP.js: Syntax Error?

### ISSUE THREAD

**Issue by jhk3** [thkl/homebridge-homematic#223]
Habe gerade die aktualisierten channelservices ausprobiert und folgendes Problem mit HomeMaticHomeKitBlindServiceIP.js beim Aufrufen von homebridge:

[2018-3-18 14:50:05] [HomeMatic CCU] Fetch Response
/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:91
  this.platform.registerAdressForEventProcessingAtAccessory(this.deviceAdress + ":3.LEVEL",this);
                ^

TypeError: this.platform.registerAdressForEventProcessingAtAccessory is not a function
    at HomeMaticHomeKitBlindServiceIP.createDeviceService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:91:17)
    at HomeMaticHomeKitBlindServiceIP.HomeKitGenericService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:69:8)
    at new HomeMaticHomeKitBlindServiceIP (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:8:41)
    at HomeMaticChannelLoader.loadChannelService (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:69:20)
    at device.channels.map.ch (/usr/lib/node_modules/homebridge-homematic/index.js:251:33)
    at Array.map (<anonymous>)
    at json.devices.map.device (/usr/lib/node_modules/homebridge-homematic/index.js:211:22)
    at Array.map (<anonymous>)
    at regarequest.script.data (/usr/lib/node_modules/homebridge-homematic/index.js:199:17)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)

**Comment by thkl** [comment]
bitte mal den kompletten Core aktualisieren. Die Funktion ist aktuell dazugekommen.
Siehe https://github.com/thkl/homebridge-homematic/wiki/Update

**Comment by jhk3** [comment]
Danke, funktioniert.
