### ISSUE TITLE
HmIP SWSD 'memyselfandi' of undefined

### ISSUE THREAD

**Issue by Stefan774** [thkl/homebridge-homematic#229]
Hallo zusammen,

ist es nur bei mir so, dass nach der Installation der neusten NPM 0.0.106. Die Rauchmelder die Rauchmelder die Homebridge zum Absturz bringen:

Folgender Fehler wird bei mir ausgegeben.

TypeError: Cannot read property 'memyselfandi' of undefined
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorServiceIP.js:26:17
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:155:34
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:326:9
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:236:7
    at Deserializer.callback (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:30:7)
    at Deserializer.onDone (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:89:12)
    at SAXStream.emit (events.js:180:13)
    at SAXParser.SAXStream._parser.onend (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:363:3)
    at SAXParser.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:209:16)
    at IncomingMessage.onend (_stream_readable.js:602:10)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)

**Comment by thkl** [comment]
Das kann einstweilen durch folgenden config.json zusätzlichen Eintrag umgangen werden:

"HmIP-SWSD:SMOKE_DETECTOR": {
  "single_alarm":false
}

**Comment by Stefan774** [comment]
Ah perfekt ich hab gerade auf 0.0.96 zurückgerollt, da ging noch alles.

Vielen Dank für die schnelle Reaktion TOP!

**Comment by thkl** [comment]
ja ich sollte wirklich vorher checken ob der schlüssel da ist, den ich lesen will ...  *seufzend*

**Comment by thkl** [comment]
Nachtrag: Austausch des Files HomeMaticHomeKitSmokeDetectorServiceIP.js in /usr/local/node_modules/homebridge-homematic/ChannelServices

durch das hier : 

https://github.com/thkl/homebridge-homematic/raw/master/ChannelServices/HomeMaticHomeKitSmokeDetectorServiceIP.js

löst das Problem

**Comment by alexduerl** [comment]
Hallo, 

habe das File "HomeMaticHomeKitSmokeDetectorServiceIP.js" bereits wie hier beschrieben ausgetauscht.

Bekomme nun einen anderen Fehler:

/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorServiceIP.js:26
      switch (newValue) {
              ^

ReferenceError: newValue is not defined
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorServiceIP.js:26:15
    at HomeMaticHomeKitSmokeDetectorServiceIP.HomeKitGenericService.query (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:170:9)
    at HomeMaticHomeKitSmokeDetectorServiceIP.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorServiceIP.js:22:10)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:162:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:756:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:720:8)
    at emitMany (events.js:108:13)

Hier scheint es noch ein Problem mit der Variable "newValue" zu geben.

Danke vorab!
