### ISSUE TITLE
HmIP-SWSD: "newValue is not defined"

### ISSUE THREAD

**Issue by alexduerl** [thkl/homebridge-homematic#232]
Hallo,

habe das File "HomeMaticHomeKitSmokeDetectorServiceIP.js" bereits wie in #229 beschrieben ausgetauscht.

Bekomme nun einen anderen Fehler:

/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorServiceIP.js:26
switch (newValue) {
^

ReferenceError: newValue is not defined
at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorServiceIP.js:26:15
at HomeMaticHomeKitSmokeDetectorServiceIP.HomeKitGenericService.query (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:170:9)
at HomeMaticHomeKitSmokeDetectorServiceIP. (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorServiceIP.js:22:10)
at emitThree (events.js:97:13)
at emit (events.js:175:7)
at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:162:10)
at Bridge. (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:756:20)
at Array.forEach (native)
at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:720:8)
at emitMany (events.js:108:13)

Hier scheint es noch ein Problem mit der Variable "newValue" zu geben.

Danke vorab!

**Comment by thkl** [comment]
bitte noch mal tauschen ... ich hab das gerade eingestellt.
Da war noch ein Fehler, der auch durch den automatischen Unittest nicht gefunden wurde ...

**Comment by alexduerl** [comment]
... läuft! Danke!
