### ISSUE TITLE
Exception beim Starten eines Programmes nach letztem Update auf 108

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#235]
Hallo, seitdem ich heute morgen auf die neuste Version 108 geupdatet habe gibt das Starten meines Programms eine Exception, vor dem Update hat das funktioniert:

```
[3/20/2018, 6:03:39 AM] [HomeMatic CCU2] NPM 0.0.108 vs Local 0.0.108
[3/20/2018, 6:04:44 AM] [HomeMatic CCU2] Launch Program Raffstores EG kippen
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSwitchService.js:81
        cc.setValue(0, null);
        ^

ReferenceError: cc is not defined
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSwitchService.js:81:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

```

**Comment by thkl** [comment]
sollte in 0.0.109 wieder gehen
