### ISSUE TITLE
Fehler in 0.0.109 (Syntax Error in HomeMaticHomeKitThermometerService.js)

### ISSUE THREAD

**Issue by roe1974** [thkl/homebridge-homematic#273]
Hi
Habe gerade von 0.0.95 auf 0.0.109 upgedatet ......

homebridge startet nicht mehr mit folgendem Fehler:

homebridge-raspi homebridge[3511]: /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:47
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: }
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: ^
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: SyntaxError: missing ) after argument list
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at createScript (vm.js:80:10)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at Object.runInThisContext (vm.js:139:10)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at Module._compile (module.js:616:28)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at Object.Module._extensions..js (module.js:663:10)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at Module.load (module.js:565:32)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at tryModuleLoad (module.js:505:12)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at Function.Module._load (module.js:497:3)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at Module.require (module.js:596:17)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at require (internal/module.js:11:18)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at HomeMaticChannelLoader.loadClass (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:109:10)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at HomeMaticChannelLoader.loadChannelService (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:66:22)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at device.channels.map.ch (/usr/lib/node_modules/homebridge-homematic/index.js:340:22)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at Array.map (<anonymous>)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at json.devices.map.device (/usr/lib/node_modules/homebridge-homematic/index.js:300:21)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at Array.map (<anonymous>)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at HomeMaticPlatform.buildaccesories (/usr/lib/node_modules/homebridge-homematic/index.js:288:16)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at regarequest.script.data (/usr/lib/node_modules/homebridge-homematic/index.js:234:9)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at emitNone (events.js:111:20)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at IncomingMessage.emit (events.js:208:7)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at endReadableNT (_stream_readable.js:1064:12)
Apr 28 19:55:15 homebridge-raspi homebridge[3511]: at _combinedTickCallback (internal/process/next_tick.js:138:11)

ist da ein fehelr in der "HomeMaticHomeKitThermometerService.js" ???

lg Richard

**Comment by roe1974** [comment]
gerade hier gesucht....

https://github.com/thkl/homebridge-homematic/issues/238

... dürfte nicht gefixt sein ;-)

weiters ist mir aufgefallen dass beim start der homebridge, nachdem alle HM Geräte im log angezeigt werden die kontrolle Zeile jetzt feht "58 Geräte wurden hinzugefügt" ... gibt es die nicht mehr ?

lg Richard

**Comment by franzel61** [comment]
Hallo Richard,
Versuche es mit 247#

Lg Franzel

**Comment by wendy2702** [comment]
Hi,

ich hänge mich hier mal ran. Habe heute Homebridge neu installiert und hatte beim Start auch diese Fehlermeldung: `/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:47`

Habe dann auch das File ausgetauscht aber bekomme jetzt diesen Fehler:

````root@iobroker-garage-gross:~/.homebridge# homebridge
[2018-5-28 16:38:30] Loaded plugin: homebridge-homematic
[2018-5-28 16:38:30] Registering platform 'homebridge-homematic.HomeMatic'
[2018-5-28 16:38:30] ---
[2018-5-28 16:38:30] Loaded config.json with 0 accessories and 1 platforms.
[2018-5-28 16:38:30] ---
[2018-5-28 16:38:30] Loading 1 platforms...
[2018-5-28 16:38:30] [HomeMatic CCU] Initializing HomeMatic platform...
[2018-5-28 16:38:30] [HomeMatic CCU] Homematic Plugin Version 0.0.109
[2018-5-28 16:38:30] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[2018-5-28 16:38:30] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[2018-5-28 16:38:30] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[2018-5-28 16:38:30] [HomeMatic CCU] running in production mode
[2018-5-28 16:38:30] [HomeMatic CCU] will connect to your ccu at 192.168.178.8
[2018-5-28 16:38:30] [HomeMatic CCU] using binrpc for communication with BidCos-RF
[2018-5-28 16:38:30] [HomeMatic CCU] init RPC for BidCos-RF.
[2018-5-28 16:38:30] [HomeMatic CCU] local ip used : 192.168.178.71. you may change that with local_ip parameter in config
[2018-5-28 16:38:30] Loading 0 accessories...
[2018-5-28 16:38:30] [HomeMatic CCU] RPC server for interface BidCos-RF. is listening on port 9090.
[2018-5-28 16:38:30] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[2018-5-28 16:38:30] [HomeMatic CCU] if PONG is PONG CCU is alive
[2018-5-28 16:38:34] [HomeMatic CCU] There is no service for HM-Dis-TD-T:STATUS_INDICATOR
[2018-5-28 16:38:34] [HomeMatic CCU] There is no service for HM-Dis-TD-T:STATUS_INDICATOR
[2018-5-28 16:38:34] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_POWER
[2018-5-28 16:38:34] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_CURRENT
[2018-5-28 16:38:34] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_VOLTAGE
[2018-5-28 16:38:34] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_FREQUENCY
/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34
  this.setCurrentStateCharacteristic(this.channelnumber + ":TEMPERATURE",this.cctemp);
       ^

TypeError: this.setCurrentStateCharacteristic is not a function
    at HomeMaticHomeKitThermometerService.createDeviceService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34:8)
    at HomeMaticHomeKitThermometerService.HomeKitGenericService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:69:8)
    at new HomeMaticHomeKitThermometerService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:9:45)
    at HomeMaticChannelLoader.loadChannelService (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
    at device.channels.map.ch (/usr/lib/node_modules/homebridge-homematic/index.js:340:22)
    at Array.map (native)
    at json.devices.map.device (/usr/lib/node_modules/homebridge-homematic/index.js:300:21)
    at Array.map (native)
    at HomeMaticPlatform.buildaccesories (/usr/lib/node_modules/homebridge-homematic/index.js:288:16)
    at regarequest.script.e (/usr/lib/node_modules/homebridge-homematic/index.js:234:9)
root@iobroker-garage-gross:~/.homebridge#```

Jemand eine Idee was ich jetzt machen kann/muss?

Danke

**Comment by bprskalo** [comment]
und wie sieht dein config aus ?

**Comment by wendy2702** [comment]
Bisher so:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "accessories": [
    ],

    "platforms": [
       {
           "platform": "HomeMatic",
           "name": "HomeMatic CCU",
           "ccu_ip": "192.168.178.8",
           "filter_device":[],
           "filter_channel":[],
           "outlets":[],
           "doors":[],
           "programs":[],
           "subsection":"Homekit"
       }
   ]
}
`

**Comment by bprskalo** [comment]
iar das "`" am schluss auch im file .. oder reingerutscht ? :-) 

sieht sonst soweit gut aus

wenn du die

"filter_device":[],
           "filter_channel":[],
           "outlets":[],
           "doors":[],
           "programs":[],


nicht brauchst

kannst du diese auch weglassen ..


hast du an der channel config etwas gemacht ?

**Comment by wendy2702** [comment]
Das ist so rein gerutscht.

Das es eine komplette neu Installation ist habe ich noch nichts weiteres gemacht außer wie geschrieben das "HomeMaticHomeKitThermometerService.js" getauscht da ich vorher den Fehler mit der ".47" am Ende hatte.

**Comment by bprskalo** [comment]
getauscht mit einer eigenen version ? änderungen in der datei gemacht ?

**Comment by wendy2702** [comment]
getauscht mit der Version die in Issue #238 und #247 erwähnt worden sind. Im File keine Änderungen gemacht.

**Comment by wendy2702** [comment]
**habe das zum testen nochmal auf einem weiteren Rechner installiert. Wenn ich Homebridge ohne config.json starte sieht es so aus:**

### homebridge
[2018-5-28 17:42:02] Loaded plugin: homebridge-homematic
[2018-5-28 17:42:02] Registering platform 'homebridge-homematic.HomeMatic'
[2018-5-28 17:42:02] ---
[2018-5-28 17:42:02] config.json (/home/pi/.homebridge/config.json) not found.
Setup Payload:
X-HM://0023ISYWYIEP3
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[2018-5-28 17:42:02] Homebridge is running on port 34353.



**Sobald ich meine config eingebe kommt dann dieser Fehler:**

homebridge
[2018-5-28 17:45:02] Loaded plugin: homebridge-homematic
[2018-5-28 17:45:02] Registering platform 'homebridge-homematic.HomeMatic'
[2018-5-28 17:45:02] ---
[2018-5-28 17:45:02] Loaded config.json with 0 accessories and 1 platforms.
[2018-5-28 17:45:02] ---
[2018-5-28 17:45:02] Loading 1 platforms...
[2018-5-28 17:45:02] [HomeMatic CCU] Initializing HomeMatic platform...
[2018-5-28 17:45:02] [HomeMatic CCU] Homematic Plugin Version 0.0.109
[2018-5-28 17:45:02] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[2018-5-28 17:45:02] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[2018-5-28 17:45:02] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[2018-5-28 17:45:02] [HomeMatic CCU] running in production mode
[2018-5-28 17:45:02] [HomeMatic CCU] will connect to your ccu at 192.168.178.8
[2018-5-28 17:45:02] [HomeMatic CCU] using binrpc for communication with BidCos-RF
[2018-5-28 17:45:02] [HomeMatic CCU] init RPC for BidCos-RF.
[2018-5-28 17:45:02] [HomeMatic CCU] local ip used : 192.168.178.71. you may change that with local_ip parameter in config
[2018-5-28 17:45:02] Loading 0 accessories...
[2018-5-28 17:45:02] [HomeMatic CCU] RPC server for interface BidCos-RF. is listening on port 9090.
[2018-5-28 17:45:02] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[2018-5-28 17:45:03] [HomeMatic CCU] if PONG is PONG CCU is alive
[2018-5-28 17:45:06] [HomeMatic CCU] There is no service for HM-Dis-TD-T:STATUS_INDICATOR
[2018-5-28 17:45:06] [HomeMatic CCU] There is no service for HM-Dis-TD-T:STATUS_INDICATOR
[2018-5-28 17:45:07] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_POWER
[2018-5-28 17:45:07] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_CURRENT
[2018-5-28 17:45:07] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_VOLTAGE
[2018-5-28 17:45:07] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_FREQUENCY
/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:47
}
^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at HomeMaticChannelLoader.loadClass (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:109:10)


**Und wenn ich dann die Datei die im Error angezeigt wird austausche erhalte ich den Fehler** 

/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34

**Comment by bprskalo** [comment]
hast du schon mal die develop version versucht ?

siehe

https://github.com/thkl/homebridge-homematic/wiki/Update


befehl zur installation 

npm install thkl/homebridge-homematic#develop -g --unsafe-perm

**Comment by wendy2702** [comment]
Ne,

noch nicht. Kann ich ja mal machen... läuft ja eh nicht also kann ich nichts kaputt spielen.

**Comment by wendy2702** [comment]
Das lässt sich zumindest mal starten 👍 

Jetzt nur noch das im logfile.

[2018-5-28 18:08:07] [HomeMatic CCU] There is no service for HM-Dis-TD-T:STATUS_INDICATOR
[2018-5-28 18:08:07] [HomeMatic CCU] There is no service for HM-Dis-TD-T:STATUS_INDICATOR
[2018-5-28 18:08:08] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_POWER
[2018-5-28 18:08:08] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_CURRENT
[2018-5-28 18:08:08] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_VOLTAGE
[2018-5-28 18:08:08] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_FREQUENCY
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:WINDOW_SWITCH_RECEIVER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:REMOTECONTROL_RECEIVER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:SWITCH_TRANSMIT
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:WINDOW_SWITCH_RECEIVER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:REMOTECONTROL_RECEIVER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:SWITCH_TRANSMIT
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:WINDOW_SWITCH_RECEIVER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:REMOTECONTROL_RECEIVER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:SWITCH_TRANSMIT
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:WINDOW_SWITCH_RECEIVER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:REMOTECONTROL_RECEIVER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-TC-IT-WM-W-EU:SWITCH_TRANSMIT
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-HUE-GTW:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-HUE-GTW:VIR-HUE-GTW-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-DIM:VIR-LG-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-DIM:VIR-LG-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGB-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGB-DIM:VIR-LG-RGB-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-RGBW-DIM:VIR-LG-RGBW-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-WHITE-DIM:VIP-MAINTENANCE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for VIR-LG-WHITE-DIM:VIR-LG-WHITE-DIM-CH
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_POWER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_CURRENT
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_VOLTAGE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_FREQUENCY
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_POWER
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_CURRENT
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_VOLTAGE
[2018-5-28 18:08:09] [HomeMatic CCU] There is no service for HM-ES-PMSw1-Pl:CONDITION_FREQUENCY
[2018-5-28 18:08:09] [HomeMatic CCU] ********************************************
[2018-5-28 18:08:09] [HomeMatic CCU] * You are using more than 100 HomeKit      *
[2018-5-28 18:08:09] [HomeMatic CCU] * devices behind a bridge. At this time    *
[2018-5-28 18:08:09] [HomeMatic CCU] * HomeKit only supports up to 100 devices. *
[2018-5-28 18:08:09] [HomeMatic CCU] * This may end up that iOS is not able to  *
[2018-5-28 18:08:09] [HomeMatic CCU] * connect to the bridge anymore.           *
[2018-5-28 18:08:09] [HomeMatic CCU] ********************************************


Und die Anzahl muss ich wohl mit Filtern reduzieren.

**Comment by bprskalo** [comment]
siehste :-) 

filter muss nicht unbedingt sein , lege "einfach" nur die geräte die du auch im Hombridge haben möchtest in der gruppe "homekit" an

das geht am einfachsten :-)

**Comment by wendy2702** [comment]
Da scheint noch ein Bug zu sein. Hatte mein Gewerk falsch geschrieben und scheinbar ließt die Bridge dann alle Geräte der CCU ein.

Nach Korrektur des Gewerk Namens klappt es.

**Comment by thkl** [comment]
Ja, ohne Gewerk wird alles zurückgeleitetet, weil der Filter halt auf * matcht.

**Comment by thkl** [comment]
kann ich den hier zu machen ?

**Comment by wendy2702** [comment]
Ich habe ja nun die DEV Version Installiert und damit schent es ja zu klappen.

Kann also meinetwegen zu.

**Comment by roe1974** [comment]
Ich weiss nicht...irgendwie ist der thread abgedriftet vom ursprünglichen Thema dass ich geöffnet habe.,.....
Ist die HomeMaticHomeKitThermometerService.js jetzt korrigiert ?

lg Richard

**Comment by franzel61** [comment]
Bei mir läuft auch alles

Mit freundlichen Gruessen / Best regards 
Franzel Rudison
