### ISSUE TITLE
Rauchmelder werden im Homekit nicht erkannt

### ISSUE THREAD

**Issue by franzel61** [thkl/homebridge-homematic#275]
Moin, moin

Ich habe versucht die Rauchmelder in Siri durch die Homebridge Zuordnung sichbar zu ... wurde nicht angezeigt, dann habe ich in die config.json den Begriff “smoke_detector” mit den SN# hinzugefügt... keine Fehleranzeige, aber auch keine Anzeige ( version ist 109 und läuft unter Docker auf der Synology)

**Comment by thkl** [comment]
Welcher RM Typ ?

**Comment by xxxchris** [comment]
@thkl 
HM-Sec-SD-2 funktioniert soweit.

**Comment by xxxchris** [comment]
wobei ich auf dem "Development Branch" folgenden Fehler bekomme:
`Tue, 01 May 2018 16:31:47 GMT EventedHTTPServer [::ffff:192.168.178.31] HTTP Response is finished
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorService.js:24
    detectorstate.eventEnabled = true;
    ^

ReferenceError: detectorstate is not defined
    at HomeMaticHomeKitSmokeDetectorService.createDeviceService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorService.js:24:5)
    at HomeMaticHomeKitSmokeDetectorService.HomeKitGenericService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:105:8)
    at new HomeMaticHomeKitSmokeDetectorService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitSmokeDetectorService.js:8:49)
    at HomeMaticChannelLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
    at device.channels.map.ch (/usr/local/lib/node_modules/homebridge-homematic/index.js:357:22)
    at Array.map (native)
    at json.devices.map.device (/usr/local/lib/node_modules/homebridge-homematic/index.js:317:21)
    at Array.map (native)
    at HomeMaticPlatform.buildaccesories (/usr/local/lib/node_modules/homebridge-homematic/index.js:305:16)
    at regarequest.script.e (/usr/local/lib/node_modules/homebridge-homematic/index.js:250:9)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by thkl** [comment]
siehe https://github.com/thkl/homebridge-homematic/commit/e5a675117d2bd49f013503c4c849b9fd67a97ad2 .. Fehler ist raus ...

**Comment by xxxchris** [comment]
Jup. Läuft. 
Hab jetzt natürlich nur die Teststellung mit den SD-2.

**Comment by xxxchris** [comment]
Kannst dir auf eigene Gefahr den "developer" branch installieren, da ist der Fix implementiert. Befehl siehe Wiki --> Update

**Comment by franzel61** [comment]
Super .. funktioniert auch mit HM-SEC-SD ( developer läuft als parallel system mit dezidierten sensoren/actoren im Docker)

**Comment by franzel61** [comment]
was muss ich einfügen/austauschen … oder ist es noch zu früh?
