### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#279]
Seite heute bekomme ich beim Starten mit user `pi` meiner Instanzen bspw. mit `homebridge -P /home/pi/node_modules/homebridge-homematic -U /home/pi/homebridge` folgende Fehlermeldung. Nachdem ich dann ein `sudo chmod 777 -R /home/pi/homebridge1/persist/` gemacht habe, kommt keine Fehlermeldung mehr aber HomeKit zeigt bei allen Geräten nach wie vor "Keine Antwort" an. Version 1.0.9. Irgendeine Idee woran das liegen kann ?

```
[/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:480
            throw e;
            ^

Error: EACCES: permission denied, open '/home/pi/homebridge1/persist/AccessoryInfo.AA333DE3CE31.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:476:16)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:277:14)
    at Object.nodePersist.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:99:29)
    at AccessoryInfo.save (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:165:11)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:543:23)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:382:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
pi@raspberrypi:~ $ homebridge -P /home/pi/node_modules/homebridge-homematic -U /home/pi/homebridge2/](url)
```

**Comment by thkl** [comment]
Tja irgendwie kann das Persistent Cache nicht gelesen werden.  Das passiert ggf wenn Homebridge mal als root lief. 

Dann startet Homebridge nicht und die Geräte werden nicht publiziert.

**Comment by iuliusmaximilian** [comment]
Aber warum geht es nach dem chmod immer noch nicht auch wenn die Exception weg ist.

**Comment by iuliusmaximilian** [comment]
Ich hab jetzt alle Instanzen mit `sudo chown pi:pi -R /home/pi/homebridge1/` die Rechte verändert, die Instanzen starten jetzt wieder, aber HomeKit zeigt nach wie vor für alle Instanzen alle Geräte als "Keine Antwort" an.

**Comment by iuliusmaximilian** [comment]
@thkl Was kann ich tun, alle Homematic-Geräte zeigen "Keine Antwort" interessanter Weise nicht die Cameras und die VideoDoorBell ? Die Logs zeigen für mich im auch Debug keine Auffälligkeiten ? Irgendwas mit Cache vielleicht. Möchte nur nicht einfach was tun in der Gefahr alle Geräte, Namen etc. zu verlieren!

**Comment by iuliusmaximilian** [comment]
```
pi@raspberrypi:~/homebridge1 $ ls -l
total 112
drwxrwxrwx 2 pi pi  4096 Apr  5 17:00 accessories
-rwxrwxrwx 1 pi pi    39 May  7 11:34 BidCos-RF.OEQ0440648.pstor
-rwxrwxrwx 1 pi pi    39 May  7 11:34 BidCos-RF.OEQ0440808.pstor
-rwxrwxrwx 1 pi pi 70517 May  8 06:51 ccu.json
-rwxrwxrwx 1 pi pi  1289 Apr  7 07:25 config.json
drwxrwxrwx 2 pi pi  4096 May  7 03:24 persist
-rwxrwxrwx 1 pi pi   209 Apr  7 06:37 raspberrypi_HmIP-RF.000955699D4233:1_persist.json
-rwxrwxrwx 1 pi pi   178 Apr  5 17:03 raspberrypi_HmIP-RF.000BD5699D4B35:1_persist.json
-rwxrwxrwx 1 pi pi   178 Apr  5 17:03 raspberrypi_HmIP-RF.000BD5699D4C41:1_persist.json
-rwxrwxrwx 1 pi pi   178 Apr  5 17:03 raspberrypi_HmIP-RF.000BD5699D4C63:1_persist.json
-rwxrwxrwx 1 pi pi   178 Apr  5 17:03 raspberrypi_HmIP-RF.000BD5699D4CB7:1_persist.json
```

```
pi@raspberrypi:~/homebridge1/persist $ ls -i
132725 AccessoryInfo.AA333DE3CE31.json  184957 IdentifierCache.AA333DE3CE31.json
```
