### ISSUE TITLE
Absturz nach einiger Zeit mit 0.33

### ISSUE THREAD

**Issue by bpohvoodoo** [thkl/homebridge-homematic#29]
Fehlermeldung aus dem hombridge.err

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:363:17)
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:59:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:124:17)
    at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

**Comment by bpohvoodoo** [comment]
Möglicherweise liegt es auch an der IOS 10 Public Beta 6

**Comment by thkl** [comment]
Fehler kommt aus dem Modul : homebridge-harmonyhub
