### ISSUE TITLE
Code Error in HomeMaticHomeKitThermometerService.js

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#302]
You may want to check the file content of the called file in 0.0.109 package of homematic-homebridge on npm

```
Jul  1 23:08:45 nuc1 homebridge[18329]: /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:47
Jul  1 23:08:45 nuc1 homebridge[18329]: }
Jul  1 23:08:45 nuc1 homebridge[18329]: ^
Jul  1 23:08:45 nuc1 homebridge[18329]: SyntaxError: missing ) after argument list
Jul  1 23:08:45 nuc1 homebridge[18329]:     at createScript (vm.js:56:10)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at Object.runInThisContext (vm.js:97:10)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at Module._compile (module.js:549:28)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at Object.Module._extensions..js (module.js:586:10)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at Module.load (module.js:494:32)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at tryModuleLoad (module.js:453:12)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at Function.Module._load (module.js:445:3)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at Module.require (module.js:504:17)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at require (internal/module.js:20:19)
Jul  1 23:08:45 nuc1 homebridge[18329]:     at HomeMaticChannelLoader.loadClass (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:109:10)
```

I needed to add }) and change a "this" into "that".

In Github these errors were fixed 3 momtsg ago ... strange

**Comment by swarozyn** [comment]
I confirm that it's required to change 
from
```
HomeMaticHomeKitThermometerService.prototype.queryData = function() {
  var that = this;
  this.query("TEMPERATURE",function(value){
    that.addLogEntry({currentTemp:parseFloat(value)})
    //create timer to query device every 10 minutes
    this.refreshTimer = setTimeout(function(){that.queryData()}, 10 * 60 * 1000);
}

```
to 

```
HomeMaticHomeKitThermometerService.prototype.queryData = function() {
  var that = this;
  this.query("TEMPERATURE",function(value){
    that.addLogEntry({currentTemp:parseFloat(value)})
    //create timer to query device every 10 minutes
    that.refreshTimer = setTimeout(function(){that.queryData()}, 10 * 60 * 1000);
})}
```

**Comment by Apollon77** [comment]
Something is wrong in current npm version.

**Comment by thkl** [comment]
the npm is not in sync with the github, because i do not build a new npm on every commit ...

**Comment by Apollon77** [comment]
Ok, but Version wise this was an older change on GitHub. But maybe good idea to bring in sync again ;-)

**Comment by thkl** [comment]
yes, currently i am doing a huge rewrite of all the code to comply with JS Standard ... there will be a new npm if all tests went to green and the system is stable on my test install ...
