### ISSUE TITLE
Garagentor -  "address_actor_close" -> Absturz homebridge

### ISSUE THREAD

**Issue by ekla** [thkl/homebridge-homematic#307]
Hi.

Erstmal vielen Dank für Deine Arbeit! Kann man sich evtl. monetär dankbar erweisen (spenden)?

Wollte einen möglichen bug reporten. Habe bis jetzt nichts dazu gefunden:

In meiner config bringt die Angabe von "address_actor_close" die homebridge zu Absturz. Auch wenn ich den selben Aktor angebe, den ich zum öffenen benutze. Ohne die Angabe funktioniert alles fehlerfrei.

Homebridge terminiert in dem Moment, in dem ich die "Schließen"-aktion ausführe mit:

```
/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:266
    let parts = addressdatapoint.split('.')
                                 ^

TypeError: addressdatapoint.split is not a function
    at HomeMaticHomeKitGarageDoorService.remoteSetDatapointValue (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:266:34)
    at HomeMaticHomeKitGarageDoorService.sendActorMessage (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitGarageDoorService.js:202:12)
    at HomeMaticHomeKitGarageDoorService.<anonymous> (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitGarageDoorService.js:167:14)
    at emitMany (events.js:147:13)
    at Characteristic.TargetDoorState.emit (events.js:224:7)
    at Characteristic.TargetDoorState.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at emitMany (events.js:147:13)
```

_config **ok**:_
```
"parameter" : {
        "address_sensor_close": "BidCos-RF.MEQ0000001:1.STATE",
        "state_sensor_close": false,
        "address_actor_open": "BidCos-RF.NEQ0000123:1.STATE",
        "message_actor_open": {"on":true,"off":false},
        "message_actor_close": {"on":true,"off":false},
        "delay_actor_open": 1,
        "delay_actor_close": 1,
        "sensor_requery_time": 30
} 
```
_config **crash** bei Schaltung:_
```
"parameter" : {
        "address_sensor_close": "BidCos-RF.MEQ0000001:1.STATE",
        "state_sensor_close": false,
        "address_actor_open": "BidCos-RF.NEQ0000123:1.STATE",
        "address_actor_close": "BidCos-RF.NEQ0000123:3.STATE",
        "message_actor_open": {"on":true,"off":false},
        "message_actor_close": {"on":true,"off":false},
        "delay_actor_open": 1,
        "delay_actor_close": 1,
        "sensor_requery_time": 30
} 
```

node: 8.11.3
homebridge: 0.4.44
homebridge-homematic@0.0.109

Danke und Gruß,
Bjoern

**Comment by thkl** [comment]
Moin,

ich glaube ich habe den Fehler gefunden.

https://github.com/thkl/homebridge-homematic/blob/master/ChannelServices/HomeMaticHomeKitGarageDoorService.js#L167-L168

Hier muss es richtig heissen:

` that.sendActorMessage(that.address_actor_close, that.message_actor_close['on'])
          that.sendActorMessage(that.address_actor_close, that.message_actor_close['off'], that.delay_actor_close)
`
Ich update das mal

**Comment by ekla** [comment]
Herzlichen Dank, @thkl .

Funktioniert nun fehlerfrei in meiner Installation (manuell editiert).
