### ISSUE TITLE
Nach Neuinstallation Fehler HomeMaticHomeKitThermometerService.js 

### ISSUE THREAD

**Issue by riconr1** [thkl/homebridge-homematic#324]
Ich erhalte unten stehende Fehlermeldung direkt nach der Installation. Auch der Austausch mit der Datei "HomeMaticHomeKitThermometerService.js "aus dem Satz von "Code" bringt diesen Fehler. Homebridge startet nicht. Lösche ich die Datei, startet Homebridge und funktioniert auch. Es gibt lediglich einen gelben Fehler, weil die Datei fehlt.

Was muss ich in der aktuellen HomeMaticHomeKitThermometerService.js  anpassen, damit es funktiert?

`/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34
  this.setCurrentStateCharacteristic(this.channelnumber + ":TEMPERATURE",this.cctemp);
       ^

TypeError: this.setCurrentStateCharacteristic is not a function
    at HomeMaticHomeKitThermometerService.createDeviceService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34:8)
    at HomeMaticHomeKitThermometerService.HomeKitGenericService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:69:8)
    at new HomeMaticHomeKitThermometerService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:9:45)
    at HomeMaticChannelLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
    at device.channels.map.ch (/usr/local/lib/node_modules/homebridge-homematic/index.js:340:22)
    at Array.map (<anonymous>)
    at json.devices.map.device (/usr/local/lib/node_modules/homebridge-homematic/index.js:300:21)
    at Array.map (<anonymous>)
    at HomeMaticPlatform.buildaccesories (/usr/local/lib/node_modules/homebridge-homematic/index.js:288:16)
    at regarequest.script.data (/usr/local/lib/node_modules/homebridge-homematic/index.js:234:9)
`

**Comment by thkl** [comment]
siehe https://github.com/thkl/homebridge-homematic/issues/273

**Comment by riconr1** [comment]
Leider hilft mir das nicht weiter. Ich habe die Datei schon getauscht. Fehler bleibt. Wo bekomme ich den die funktionierende Datei her? Und der aktuellen Repo ist sie ja defekt, oder?

**Comment by thkl** [comment]
Es hilft nicht das File zu tauschen, weil dieses eine Funktion der Superklasse referenziert, welches es nicht gibt ... du müsstest das komplette dev Repo benutzen

**Comment by riconr1** [comment]
Kann ich durch ein Kommando die Daten komplett vom Raspberry ziehen lassen oder geht das nur von Hand? 
Sonst soll ich die gesamte dev Repo per Filezilla überspielen? 

Sorry, dass ich mich nicht so zurechtfinde. Ich gelobe Besserung.

**Comment by t-rex-2000** [comment]
npm install thkl/homebridge-homematic#master -g --unsafe-perm dieser befehl half bei mir, seitdem alles wieder gut

**Comment by CptChristo** [comment]
Was hilft ist Zeile 34 in der Datei HomeMaticHomeKitThermometerService.js aus zu kommentieren.
Es heißt dann:
...
32  }.bind(this));
33
34  //this.setCurrentStateCharacteristic(this.channelnumber + ":TEMPERATURE",this.cctemp);
35  this.eventEnabled = true;
..

Problem ist, dass ich keine Ahnung habe, was das Fehlen des Aufrufs für Konsequenzen hat...
