### ISSUE TITLE
Homebridge startet nach Installation nicht

### ISSUE THREAD

**Issue by mkinberger** [thkl/homebridge-homematic#331]
Ich habe ein neues System ausgesetzt.
Nach der Installation von Homebridge-homematic startet die Homebridge nicht mehr.

Folgender Fehler erscheint im Log-File:
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:47
}
^

SyntaxError: missing ) after argument list
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)

**Comment by Duude4711** [comment]
D.h., die "nackte" Homebridge Installation lief ohne Probleme durch? Erst nach der Installation des Homebridge-Homematic Plugins stürzt sie ab? Prüfe bestenfalls die config.json nochmal, da ist häufig ein Fehler drin, wenn die HB nicht richtig durchstartet.

**Comment by t-rex-2000** [comment]
ich habe selbes problem. wenn ich die "subsection" : "Homekit", entferne, läuft das plugin und die homebridge. gebe ich das gewerk wieder ein, zack absturz.

**Comment by t-rex-2000** [comment]
das sollte die lösung sein npm install thkl/homebridge-homematic#master -g --unsafe-perm
