### ISSUE TITLE
Exception bei Variablen nach Update auf CCU3

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#345]
Hallo zusammen, ich bekomme nach dem Update von der CCU2 > CCU3 folgende Fehlermeldung und Variablen sind in Home nicht erreichbar:

```
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("Alarm");if (d){Write(d.State());}
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("Anwesenheit");if (d){Write(d.State());}
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("Reboot RasPi.STATE");if (d){Write(d.State());}
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("ProgrammStarter_Raffstores_OG_Minimal_Kippen");if (d){Write(d.State());}
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("ProgrammStarter_Raffstores_OG_Kippen");if (d){Write(d.State());}
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("ProgrammStarter_Raffstores_EG_Lueften");if (d){Write(d.State());}
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("ProgrammStarter_Raffstores_EG_Halb_Kippen");if (d){Write(d.State());}
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("ProgrammStarter_Raffstores_EG_Kippen");if (d){Write(d.State());}
[2018-10-23 21:00:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script var d = dom.GetObject("Sicherheit");if (d){Write(d.State());}
[2018-10-23 21:01:00] [HomeMatic CCU2] timeout while executing rega script
[2018-10-23 21:01:00] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script WriteLine('Anwesenheit(---)'#dom.GetObject('Anwesenheit').State());WriteLine('Alarm(---)'#dom.GetObject('Alarm').State());WriteLine('Sicherheit(---)'#dom.GetObject('Sicherheit').State());WriteLine('ProgrammStarter_Raffstores_EG_Kippen(---)'#dom.GetObject('ProgrammStarter_Raffstores_EG_Kippen').State());WriteLine('ProgrammStarter_Raffstores_EG_Halb_Kippen(---)'#dom.GetObject('ProgrammStarter_Raffstores_EG_Halb_Kippen').State());WriteLine('ProgrammStarter_Raffstores_EG_Lueften(---)'#dom.GetObject('ProgrammStarter_Raffstores_EG_Lueften').State());WriteLine('ProgrammStarter_Raffstores_OG_Kippen(---)'#dom.GetObject('ProgrammStarter_Raffstores_OG_Kippen').State());WriteLine('ProgrammStarter_Raffstores_OG_Minimal_Kippen(---)'#dom.GetObject('ProgrammStarter_Raffstores_OG_Minimal_Kippen').State());
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitVariableUpdaterService.js:30
    		   result.split("\r\n").map( function(tmpvar) {
    		          ^

TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitVariableUpdaterService.js:30:17
    at rega.script.data (/usr/local/lib/node_modules/homebridge-homematic/index.js:569:4)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:50:9)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketCloseListener (_http_client.js:363:9)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12)
```

**Comment by iuliusmaximilian** [comment]
Nach dem Start der Bridge kam auch schon eine Meldung:

```
[2018-10-23 20:58:57] Homebridge is running on port 51822.
[2018-10-23 20:58:57] [HomeMatic CCU2] Error Error: socket hang upwhile executing rega script Write('PONG')
[2018-10-23 20:58:57] [HomeMatic CCU2] if undefined is PONG CCU is alive
```

**Comment by iuliusmaximilian** [comment]
Fehler gefunden! Beim Backup Wiedereinspielen auf der CCU3 wurden die IP-Sicherheitseinstellungen nicht übernommen.
