### ISSUE TITLE
HomeApp zeigt "Aktualisieren" / nicht erreichtbar - response timeout bei init BidCos-RF with xmlprc und RPC getValue

### ISSUE THREAD

**Issue by s-d-koenig** [thkl/homebridge-homematic#348]
Hallo zusammen,

ich hab ein mir nicht verständliches Problem mit der Kommunikation zwischen Homebridge-Homematic auf einem Raspi und der CCU.

Debug zeigt:

[2018-11-2 18:05:54] [HomeMatic CCU] will cache ccu response to /home/pi/.homebridge/ccu.json
[2018-11-2 18:05:56] [HomeMatic CCU] NPM 0.0.109 vs Local 0.0.109
[2018-11-2 18:05:58] [HomeMatic CCU] CCU Response for init at BidCos-RF. with xmlrpc_bin://192.168.1.18:9090...Value (undefined) Error : (Error: response timeout)
[2018-11-2 18:06:03] [HomeMatic CCU] RPC getValue (JEQ0202085:1 LEVEL) Response undefined Errors: Error: response timeout

Historie:
Ich habe Homebridge gestern auf dem Raspi installiert und erstmal wenige HM-Geräte auf der CCU dem Gewerk hinzugefügt. Das lief!

Danach habe ich - leider parallel - die CCU3 auf 3.41.7 upgedated und einige Geräte dem Gewerk hinzugefügt (jetzt in Summe 21).
Danach ging es nicht mehr. Da mich einige andere Artikel und rumprobieren nicht weiterbrachten, zähle ich jetzt auf Euch.

**Comment by iuliusmaximilian** [comment]
Habe das gleiche Problem mit der neuen Firnware. Obwohl ich alle Sicherheitseinstellungen komplett freigeschaltet hatte, keine Verbindung. Downgrade der Firmware und wieder einspielen des Backups der CCU3 und alles lief wieder. Allerdings hat Homebridgw einige / nicht alle Komponenten als neue Geräte identifiziert was ärgerlich war.

**Comment by s-d-koenig** [comment]
Danke - das hilft schon mal. Dann warte ich mal eine Woche, ob sich das Problem lösen lässt (von welcher Seite auch immer). Da es noch nicht lief, werde ich es noch nicht vermissen.
Falls ich bei der Lösung helfen kann, indem ich was teste, kann ich das gern tun.

**Comment by thkl** [comment]
Ich habe leider keine CCU3 zum Test. Ich werde das mal mit der aktuellen Raspberrymatic Software ausprobieren ... zumindest scheint die CCU nicht mehr auf RPC Inits zu reagieren. Da gibt es keinen Workaround denn dieser Call ist essentiell, da damit die Events der CCU (Also Zustandsänderungen der Geräte) dem Plugin mitgeteilt werden.

**Comment by hypertom** [comment]
Der CCU-Historian hat das gleiche Problem und hat bereits eine Lösung erarbeitet. Die Kommunikation muss wohl auf eine andere Methode umgestellt werden. Details sind beim CCU-Historian zu finden. 
https://github.com/mdzio/ccu-historian/issues/136

**Comment by thkl** [comment]
https://github.com/thkl/homebridge-homematic/commit/04b9e25318e9ff93f8ea8e88fbf1e8b54da24076

**Comment by jp112sdl** [comment]
Läuft es nur unter der **3.41.x** zuverlässig?
Ich habe noch die **3.37** und wollte schon mal auf xmlrpc umstellen, jedoch stürzt die homebridge exakt **alle 30 Minuten** ab:
```
Nov 18 05:42:14 localhost homebridge[15814]: /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:144
Nov 18 05:42:14 localhost homebridge[15814]:           that.platform.eventAdresses.map(function (tuple) {
Nov 18 05:42:14 localhost homebridge[15814]:                                       ^
Nov 18 05:42:14 localhost homebridge[15814]: TypeError: Cannot read property 'map' of undefined
Nov 18 05:42:14 localhost homebridge[15814]:     at Server.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:144:39)
Nov 18 05:42:14 localhost homebridge[15814]:     at emitThree (events.js:136:13)
Nov 18 05:42:14 localhost homebridge[15814]:     at Server.emit (events.js:217:7)
Nov 18 05:42:14 localhost homebridge[15814]:     at /usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/server.js:42:14
Nov 18 05:42:14 localhost homebridge[15814]:     at Deserializer.callback (/usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:65:7)
Nov 18 05:42:14 localhost homebridge[15814]:     at Deserializer.onDone (/usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
Nov 18 05:42:14 localhost homebridge[15814]:     at emitNone (events.js:106:13)
Nov 18 05:42:14 localhost homebridge[15814]:     at SAXStream.emit (events.js:208:7)
Nov 18 05:42:14 localhost homebridge[15814]:     at SAXParser.SAXStream._parser.onend (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:171:8)
Nov 18 05:42:14 localhost homebridge[15814]:     at emit (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)
```

Habe nun erstmal wieder auf die originale *binrpc* Version gewechselt.
Ich möchte nur ausschließen, dass noch irgendwas andere in meinem System im Argen liegt.

@thkl 
> Schade das EQ3 so mit seiner Community umgeht.

Leider erhält man mittlerweile immer häufiger mit jeder neuen FW ein Überraschungspaket 👎
