### ISSUE TITLE
Homebridge hängt sich nach einigen Stunden auf

### ISSUE THREAD

**Issue by AdlerCentauri** [thkl/homebridge-homematic#359]
Hallo, bei mir scheint sich die Homebridge nach ca. einer Stunde aufzuhängen.

Siri sagt dann nur noch "Ich überprüfe immer noch deine Geräte" und in der Home App steht bei den Geräten "Keine Antwort"

Welche Infos muss ich liefern und wo hole ich die, um dem Problem auf die schliche zu kommen?

Danke

**Comment by AdlerCentauri** [comment]
Niemand der helfen kann? Sie stürzt leider immer wieder ab.

**Comment by JensBonse** [comment]
Welche Plugins laufen denn alles auf deiner HomeBridge?
Schon mal probiert einige zu deaktivieren um es einzugrenzen?
Was steht denn im Log?

**Comment by AdlerCentauri** [comment]
Das Harmony Plugin sonst keins. Das werde ich mal deaktivieren. Aber bisher hat es nie Probleme gemacht.

**Comment by JensBonse** [comment]
Wenn es das nicht ist, dann müsste man sich das Log ansehen.

**Comment by AdlerCentauri** [comment]
das ist erstmal die homebridge.error ist da was brauchbares bei?

```
Unhandled rejection TypeError: Cannot read property 'result' of undefined
    at /usr/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-client/lib/harmonyclient.js:72:29
    at _fulfilled (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/q/q.js:816:13)
    at /usr/lib/node_modules/homebridge-harmonyhub/node_modules/q/q.js:624:44
    at runSingle (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:116:13)
    at StreamParser.emit (events.js:211:7)
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:116:13)
    at SaxLtx.emit (events.js:211:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:116:13)
    at StreamParser.emit (events.js:211:7)
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:116:13)
    at SaxLtx.emit (events.js:211:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitContactService.js:118:8
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:188:34
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:357:9
    at /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:245:7
    at Object.callback (/usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:195:25)
    at /usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:171:29
    at _combinedTickCallback (internal/process/next_tick.js:136:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: MAX_CLIENTS=6
    at Connection.onStanza (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:116:13)
    at StreamParser.emit (events.js:211:7)
    at SaxLtx.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:116:13)
    at SaxLtx.emit (events.js:211:7)
    at SaxLtx._handleTagOpening (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
    at Connection.onData (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-core/lib/Connection.js:305:17)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
sudo: Hostname hvl-server kann nicht aufgelöst werden: Verbindungsaufbau abgelehnt
[2018-11-27 21:13:35] [HomeMatic CCU] Error Error: connect ENETUNREACH 192.168.191.20:8181 - Local (0.0.0.0:0)while executing rega script Write('PONG')
[2018-11-27 21:13:35] [HomeMatic CCU] Error Error: connect ENETUNREACH 192.168.191.20:8181 - Local (0.0.0.0:0)while executing rega script string sDeviceId;string sChannelId;boolean df = true;Write('{"devices":[');foreach(sDeviceId, root.Devices().EnumIDs()){object oDevice = dom.GetObject(sDeviceId);if(oDevice){var oInterface = dom.GetObject(oDevice.Interface());if(df) {df = false;} else { Write(',');}Write('{');Write('"id": "' # sDeviceId # '",');Write('"name": "' # oDevice.Name() # '",');Write('"address": "' # oDevice.Address() # '",');Write('"type": "' # oDevice.HssType() # '",');Write('"channels": [');boolean bcf = true;foreach(sChannelId, oDevice.Channels().EnumIDs()){object oChannel = dom.GetObject(sChannelId);if(bcf) {bcf = false;} else {Write(',');}Write('{');Write('"cId": ' # sChannelId # ',');Write('"name": "' # oChannel.Name() # '",');if(oInterface){Write('"intf": "' # oInterface.Name() 	# '",');Write('"address": "' # oInterface.Name() #'.' # oChannel.Address() # '",');}Write('"type": "' # oChannel.HssType() # '",');Write('"access": "' # oChannel.UserAccessRights(iulOtherThanAdmin)# '"');Write('}');}Write(']}');}}Write(']');var s = dom.GetObject("homekit");string cid;boolean sdf = true;if (s) {Write(',"subsection":[');foreach(cid, s.EnumUsedIDs()){  if(sdf) {sdf = false;} else { Write(',');}Write(cid);}Write(']');}Write('}');
[2018-11-27 21:15:43] [HomeMatic CCU] timeout while executing rega script
[2018-11-27 21:15:43] [HomeMatic CCU] timeout while executing rega script
[2018-11-28 00:21:14] [HomeMatic CCU] client missing
[2018-11-28 00:21:24] [HomeMatic CCU] client missing
[2018-11-28 00:21:28] [HomeMatic CCU] client missing
[2018-11-28 10:14:23] [HomeMatic CCU] client missing
[2018-11-28 10:14:23] [HomeMatic CCU] client missing
[2018-11-28 10:14:23] [HomeMatic CCU] client missing
[2018-11-28 10:14:23] [HomeMatic CCU] client missing
[2018-11-28 10:14:23] [HomeMatic CCU] client missing
[2018-11-28 10:14:23] [HomeMatic CCU] client missing
[2018-11-28 10:14:39] [HomeMatic CCU] client missing
[2018-11-28 10:14:39] [HomeMatic CCU] client missing
[2018-11-28 10:14:39] [HomeMatic CCU] client missing
[2018-11-28 10:14:39] [HomeMatic CCU] client missing
[2018-11-28 10:14:39] [HomeMatic CCU] client missing
[2018-11-28 10:14:39] [HomeMatic CCU] client missing
[2018-11-28 10:14:45] [HomeMatic CCU] client missing
[2018-11-28 10:14:45] [HomeMatic CCU] client missing
[2018-11-28 10:14:45] [HomeMatic CCU] client missing
[2018-11-28 10:14:45] [HomeMatic CCU] client missing
[2018-11-28 10:14:45] [HomeMatic CCU] client missing
[2018-11-28 10:14:45] [HomeMatic CCU] client missing
[2018-11-28 10:14:56] [HomeMatic CCU] client missing
[2018-11-28 10:14:56] [HomeMatic CCU] client missing
[2018-11-28 10:14:56] [HomeMatic CCU] client missing
[2018-11-28 10:14:56] [HomeMatic CCU] client missing
[2018-11-28 10:14:56] [HomeMatic CCU] client missing
[2018-11-28 10:14:56] [HomeMatic CCU] client missing
[2018-11-28 10:31:58] [HomeMatic CCU] client missing
/usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:315
  this.client.methodCall('init', ['xmlrpc_bin://' + this.localIP + ':' + this.listeningPort], function (error, value) {
              ^

TypeError: Cannot read property 'methodCall' of undefined
    at HomeMaticRPC.stop (/usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:315:15)
    at process.HomeMaticPlatform.process.on (/usr/lib/node_modules/homebridge-homematic/index.js:131:16)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at Signal.wrap.onsignal (internal/process.js:197:44)
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 14159177-d78c-457f-abe9-06cdfe035d7c
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:290:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:473:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at emitOne (events.js:116:13)
    at API.emit (events.js:211:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
    at /usr/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:155:15
    at PassThroughHandlerContext.finallyHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:432:57)
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:250
    throw new Error("Cannot update reachability on non-bridged accessory!");
    ^

Error: Cannot update reachability on non-bridged accessory!
    at Accessory.updateReachability (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:250:11)
    at PlatformAccessory.updateReachability (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:129:34)
    at ActivityAccessory.refreshConnection (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-accessory-base.js:56:17)
    at emitOne (events.js:121:20)
    at HubConnection.emit (events.js:211:7)
    at HubConnection._OnConnectionChanged (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:161:7)
    at HubConnection.refreshAsync (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:150:7)
    at HubConnection.refresh (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:142:7)
    at HubConnection._HandleConnectionOffline (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:137:14)
    at emitNone (events.js:106:13)
    at Client.emit (events.js:208:7)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:157:12)
    at emitOne (events.js:121:20)
    at Connection.emit (events.js:211:7)
    at Socket.onDisconnect (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/reconnect-core/index.js:59:17)
    at emitNone (events.js:111:20)
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 14159177-d78c-457f-abe9-06cdfe035d7c
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:290:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:473:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at emitOne (events.js:116:13)
    at API.emit (events.js:211:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
    at /usr/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:155:15
    at PassThroughHandlerContext.finallyHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:432:57)
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:250
    throw new Error("Cannot update reachability on non-bridged accessory!");
    ^

Error: Cannot update reachability on non-bridged accessory!
    at Accessory.updateReachability (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:250:11)
    at PlatformAccessory.updateReachability (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:129:34)
    at ActivityAccessory.refreshConnection (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-accessory-base.js:56:17)
    at emitOne (events.js:121:20)
    at HubConnection.emit (events.js:211:7)
    at HubConnection._OnConnectionChanged (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:161:7)
    at HubConnection.refreshAsync (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:150:7)
    at HubConnection.refresh (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:142:7)
    at HubConnection._HandleConnectionOffline (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:137:14)
    at emitNone (events.js:106:13)
    at Client.emit (events.js:208:7)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:157:12)
    at emitOne (events.js:121:20)
    at Connection.emit (events.js:211:7)
    at Socket.onDisconnect (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/reconnect-core/index.js:59:17)
    at emitNone (events.js:111:20)

```

**Comment by AdlerCentauri** [comment]
3.41.11. Ich habe die entsprechenden Dateien für die 3.41.11 aber ersetzt bzw. die HomeMaticRPC.js

**Comment by AdlerCentauri** [comment]
Als ich den Pi neu eingerichtet habe, habe ich "hvl-server" per raspi-config gesetzt. 

In der  /etc/hosts steht nur das:

```127.0.0.1  Homebridge```

**Comment by JensBonse** [comment]
Dann setz erst mal zusätzlich `127.0.0.1 hvl-server` in deiner hosts.

Laut dem Error Log willst du ein 'Accessory' mit der gleichen ID ein zweites Mal hinzufügen.
Poste ggf. mal deine Config.

**Comment by AdlerCentauri** [comment]
Ich habe jetzt in der raspi-config auch Homebridge eingetragen.

Wenn ich die Homebridge stoppe, dann funktioniert es genau für 2 Minuten.
Nach dem Start sieht das error Log so aus:

`Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 14159177-d78c-457f-abe9-06cdfe035d7c
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:290:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:473:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at emitOne (events.js:116:13)
    at API.emit (events.js:211:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
    at /usr/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:155:15
    at PassThroughHandlerContext.finallyHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:432:57)`

Und sobald es nicht mehr geht, sieht das .error Log so aus:
`Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 14159177-d78c-457f-abe9-06cdfe035d7c
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:290:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:473:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at emitOne (events.js:116:13)
    at API.emit (events.js:211:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
    at /usr/lib/node_modules/homebridge-harmonyhub/lib/home-platform.js:155:15
    at PassThroughHandlerContext.finallyHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/bluebird/js/release/promise.js:432:57)
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:250
    throw new Error("Cannot update reachability on non-bridged accessory!");
    ^

Error: Cannot update reachability on non-bridged accessory!
    at Accessory.updateReachability (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:250:11)
    at PlatformAccessory.updateReachability (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:129:34)
    at ActivityAccessory.refreshConnection (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-accessory-base.js:56:17)
    at emitOne (events.js:121:20)
    at HubConnection.emit (events.js:211:7)
    at HubConnection._OnConnectionChanged (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:161:7)
    at HubConnection.refreshAsync (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:150:7)
    at HubConnection.refresh (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:142:7)
    at HubConnection._HandleConnectionOffline (/usr/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:137:14)
    at emitNone (events.js:106:13)
    at Client.emit (events.js:208:7)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:157:12)
    at emitOne (events.js:121:20)
    at Connection.emit (events.js:211:7)
    at Socket.onDisconnect (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/reconnect-core/index.js:59:17)
    at emitNone (events.js:111:20)
`

**Comment by AdlerCentauri** [comment]
Das ist meine Config:

`{
	"bridge": {
		"name": "Homebridge",
		"username": "CA:32:3E:E3:CE:4D",
		"port": 51826,
		"pin": "094-73-828"
	},
	"description": "This is an autogenerated config. only the homematic platform is enabled. see the sample for more",
	"platforms": [{
			"platform": "HomeMatic",
			"name": "HomeMatic CCU",
			"enable_hmip": "true",
			"ccu_ip": "192.168.191.20",
			"subsection": [
				"homekit"
			],
			"outlets": [
				"BidCos-RF.MEQ0170956:1", "BidCos-RF.MEQ0170962:1", "BidCos-RF.LEQ0660939:1", "BidCos-RF.LEQ0930780:1", "BidCos-RF.LEQ0661729:1", "BidCos-RF.LEQ0930499:1"
			],
			"programs": []
		},
		{
			"platform": "HarmonyHub",
			"name": "Harmony Hub"
		}
	]
}`

**Comment by JensBonse** [comment]
Also in dem zweiten Log scheint 'homebridge-harmonyhub' Probleme zu machen.

**Comment by JensBonse** [comment]
Lass es mal ohne das HarmonyHub laufen. Mal schauen, ob HomeBridge dann länger als 2 Minuten schafft...

**Comment by AdlerCentauri** [comment]
Oben ist meine Config.

Komisch, HarmonyHub hat bisher nie Probleme gemacht. Ich hatte die Homebridge die ganze Zeit auf der Synology im Docker laufen, Monate lang ohne Probleme. Erst seit kurzem läuft die Homebridge auf dem Pi, und seitdem Probleme.

Ich werde den HarmonyHub dann erstmal aus der Config verbannen und schauen wie es dann läuft. Melde mich.

**Comment by JensBonse** [comment]
Ggf. ist beim Umzug von der Synology auf den PI etwas schief gelaufen und daher kennt HomeKit die alte HarmonyHub UUID noch, die sich nun aber von einem andern Gerät aus versucht zu melden.

Falls es dir möglich ist, lösch mal den kompletten Harmony Kram aus deiner HomeKit Home App.

Oder falls es nicht zu viel Konfigurationsaufwand war, dann gib lösch alles aus HomeKit, setz die HomeBridge zurück (persists Ordner löschen) und gib der HomeBridge ggf. einen neuen username (am Ende aus 4D einfach mal eine 4C oder so machen).

**Comment by AdlerCentauri** [comment]
Das war kein Umzug, habe alles neu eingerichtet inkl. anderer MAC-Adresse.

Bis jetzt läuft noch alles, ich warte aber noch mal ab. 

In der .err Log steht jetzt auch nur noch das, was ja jetzt normal ist:
`[2018-12-2 13:50:38] [homebridge-harmonyhub.HarmonyHub] Ignoring Harmony Platform setup because it is not configured`

Melde mich wieder.

**Comment by AdlerCentauri** [comment]
So, es läuft immer noch. Der Harmonyhub ist tatsächlich Schuld.

**Comment by JensBonse** [comment]
TOP!
Dann kannst du den Issue ja schließen.
