### ISSUE TITLE
starting typeerror client.js

### ISSUE THREAD

**Issue by scottyblue77** [thkl/homebridge-homematic#360]
hello, sry was searching now several hours, i get this error during start, all devices are ok and listed.. at end of start this one comes:

2018-12-3 23:06:39] Homebridge is running on port 51826.
[2018-12-3 23:06:39] [skhome] will cache ccu response to /home/pi/.homebridge/ccu.json
[2018-12-3 23:06:41] [skhome] NPM 0.0.109 vs Local 0.0.109

/usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:193
                        callback(null, binrpc.decodeResponse(res));
                        ^
TypeError: Cannot set property 'refreshTimer' of undefined
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:46:23
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:176:34
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:357:9
    at /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:236:7
    at Object.callback (/usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:193:25)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:152:33)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)

**Comment by scottyblue77** [comment]
i have ccu2 with 2.29.23

**Comment by royalflashii** [comment]
just try setting up a new homebridge and use the tutorial of this website. It works properly. https://technikkram.net/

**Comment by Fr0z3n1337** [comment]
Hi, bekomme den gleichen Fehler.
/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:193
                        callback(null, binrpc.decodeResponse(res));
                        ^
TypeError: Cannot set property 'refreshTimer' of undefined
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:46:23
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:176:34
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:357:9
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:236:7
    at Object.callback (/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:193:25)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/node_modules/binrpc/lib/client.js:152:33)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)

NPM 
root@tinkerboard:~# npm version
{ 'package.json': '1.0.0',
  npm: '6.5.0-next.0',
  ares: '1.15.0',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.0.1',
  modules: '67',
  napi: '3',
  nghttp2: '1.34.0',
  node: '11.6.0',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.24.1',
  v8: '7.0.276.38-node.13',
  zlib: '1.2.11' }

homebridge-homematic 0.0.0.109
homebridge 0.4.45

Eine Idee was ich tun könnte?

Danke
