### ISSUE TITLE
TypeError: this.setCurrentStateCharacteristic is not a function

### ISSUE THREAD

**Issue by jimmyneutron1974** [thkl/homebridge-homematic#377]
Hi, ich bekomme beim Aufruf von Homebridge folgenden Fehler:

/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34
  this.setCurrentStateCharacteristic(this.channelnumber + ":TEMPERATURE",this.cctemp);
       ^
TypeError: this.setCurrentStateCharacteristic is not a function
    at HomeMaticHomeKitThermometerService.createDeviceService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:34:8)
    at HomeMaticHomeKitThermometerService.HomeKitGenericService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:69:8)
    at new HomeMaticHomeKitThermometerService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermometerService.js:9:45)
    at HomeMaticChannelLoader.loadChannelService (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
    at device.channels.map.ch (/usr/lib/node_modules/homebridge-homematic/index.js:340:22)
    at Array.map (<anonymous>)
    at json.devices.map.device (/usr/lib/node_modules/homebridge-homematic/index.js:300:21)
    at Array.map (<anonymous>)
    at HomeMaticPlatform.buildaccesories (/usr/lib/node_modules/homebridge-homematic/index.js:288:16)
    at regarequest.script.data (/usr/lib/node_modules/homebridge-homematic/index.js:234:9)

**Comment by jimmyneutron1974** [comment]
Vorher habe ich folgenden Fix probiert: https://github.com/thkl/homebridge-homematic/issues/238

**Comment by OmniNotitia** [comment]
Ich habe das gleiche Problem.
=> Neuinstallation.
Zuerst #238 gefolgt durch #377 nach dem Hotfix für #238

**Comment by preacha** [comment]
Ich habe das gleiche Problem, gibts es hier schon einen fix?
