### ISSUE TITLE
Video DoorBell

### ISSUE THREAD

**Issue by legerp** [thkl/homebridge-homematic#396]
Hallo,
ich füge gerade ein Türklingel hinzu aber irgendwas stimmt noch nicht. Kann jemand helfen?
habe die homebridge soeben aktualisiert.

Fehler;
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitDoorBellVideoService.js:158
  this.platform.api.publishCameraAccessories(this.name, [doorbell_accessory]);
                    ^
TypeError: Cannot read property 'publishCameraAccessories' of undefined
    at HomeMaticHomeKitDoorBellVideoService.setup (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitDoorBellVideoService.js:158:21)
    at new HomeMaticHomeKitDoorBellVideoService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitDoorBellVideoService.js:11:10)
    at HomeMaticChannelLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:95:19)
    at that.specialdevices.map.specialdevice (/usr/local/lib/node_modules/homebridge-homematic/index.js:386:19)
    at Array.map (<anonymous>)
    at HomeMaticPlatform.buildaccesories (/usr/local/lib/node_modules/homebridge-homematic/index.js:378:23)
    at regarequest.script.data (/usr/local/lib/node_modules/homebridge-homematic/index.js:234:9)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:43:9)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)

**Comment by legerp** [comment]
Fehler gefunden. Update von homebridge-homematic hilft ungemein....
