### ISSUE TITLE
TypeError: "list" argument must be an Array of Buffers

### ISSUE THREAD

**Issue by in60-code** [thkl/homebridge-homematic#424]
Hi, 

ich habe meine CCU2 geupdatet.
Aktuelle Firmwareversion: 2.45.7
Homematic Plugin Version 0.0.109
node Version v6.17.1

Nun erhalte ich beim Start von Homebridge folgende Fehlermeldung

[2019-5-12 20:20:31] Homebridge is running on port 51826.
[2019-5-12 20:20:31] [HomeMatic CCU] will cache ccu response to /home/pi/.homebridge/ccu.json
[2019-5-12 20:20:32] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairVerifyStepOne (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:543:21)
    at HAPServer._handlePairVerify (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:505:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
[2019-5-12 20:20:32] Got SIGTERM, shutting down Homebridge...
[2019-5-12 20:20:32] [HomeMatic CCU] Removing Event Server for Interface BidCos-RF.

Die Datei /home/pi/.homebridge/ccu.json habe ich bereits mal geleert, leider ohne Erfolg.

Könnt ihr mir helfen, wo hier der Fehler liegt?

Viele Grüße
in60

**Comment by dkrizic** [comment]
Habe ich auch, wenn ich die aktuelle Version von Homebridge (selbst) installiere. ich bin mit ppm -g install homebridge@0.4.46 auf eine ältere Version gegangen, damit ist der Fehler weg.

**Comment by dkrizic** [comment]
Ich habe das Problem gelöst, indem ich Node von 6.x auf 10.x aktualisiert habe. Damit ist diese Meldung weg. Das Problem hat nichts mit homebridge-homematic zu tun, sondern direkt mit Homebridge.

**Comment by in60-code** [comment]
Das Update auf Node 10.x hat bei mir auch das Problem behoben!
Besten Dank für den Hinweis! :-)
