### ISSUE TITLE
TypeError: Service.DoorStateService is not a function

### ISSUE THREAD

**Issue by Apollon77** [thkl/homebridge-homematic#45]
I have newly installed homebridge on a node 4.x system and upgraded to 0.0.43.
So i created a subsection.

Now I get:
[10/11/2016, 9:22:42 PM] [HomeMatic CCU2] Fetching Homematic devices...
[10/11/2016, 9:22:42 PM] Loading 0 accessories...
/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitRotaryHandleService.js:51
      var door = new Service["DoorStateService"](this.name);
                 ^

TypeError: Service.DoorStateService is not a function
    at HomeMaticHomeKitRotaryHandleService.createDeviceService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitRotaryHandleService.js:51:18)
    at HomeMaticHomeKitRotaryHandleService.HomeKitGenericService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:50:8)
    at new HomeMaticHomeKitRotaryHandleService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitRotaryHandleService.js:8:48)
    at HomeMaticChannelLoader.loadChannelService (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:44:20)
    at /usr/lib/node_modules/homebridge-homematic/index.js:253:33
    at Array.map (native)
    at /usr/lib/node_modules/homebridge-homematic/index.js:212:32
    at Array.map (native)
    at /usr/lib/node_modules/homebridge-homematic/index.js:197:25
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:41:9)

**Comment by thkl** [comment]
fixed this in version 0.0.44
