### ISSUE TITLE
Nach update der RasberryMatic keine rückantwort für Variablenänderung inm der HomeBridge

### ISSUE THREAD

**Issue by Marco4223** [thkl/homebridge-homematic#472]
Hallo Thomas,
sorry das ich das als Bug aufmache, aber das Forum scheint mich nicht zu mögen und ich kann für mein Problem keine Antwort finden. 

Aktuell habe ich es nach langem Suchen es hinbekommen das ich meine CCU/RasberryMatic auf die neuste Version (RaspberryMatic 3.47.22.20191026) angehoben bekommen habe und (fast) alles wieder läuft. 
Auch Programme werden nun endlich sauber gestartet. Allerdings klappt die Kommunikation (RasberryMatic  -> HomeBridge) mit der HomeBridge nicht mehr. Ich kann zwar Variablen in der „CCU“ ansteuern aber bei Änderungen dieser (CCU setzt diese nach ein paar Sekunden zurück) bekommt dieses die HomeBridge nicht mit. Bzw. auf dem iOS wird es nicht aktualisiert. Im Forum lese ich immer wieder dieses hier: "Wenn das deine erste 3.41.x Version ist solltest du dich erst einmal mit den fundamentalen Änderungen in sachen geändeter Firewall/Authentifizierung etc. beschäftigen."
Aber es macht nicht klick. Würde mich freuen, wenn Du mich "Erleuchten" könntest!?
Hier einmal mein Log:  

`root@cubietruck:~# homebridge -D
[11/8/2019, 4:29:06 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/8/2019, 4:29:06 PM] ---
[11/8/2019, 4:29:08 PM] Loaded plugin: homebridge-homematic
[11/8/2019, 4:29:08 PM] Registering platform 'homebridge-homematic.HomeMatic'
[11/8/2019, 4:29:08 PM] ---
[11/8/2019, 4:29:08 PM] Loading 1 platforms...
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Initializing HomeMatic platform...
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Homematic Plugin Version 0.0.109
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Plugin by thkl  https://github.com/thkl
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Homematic is a registered trademark of the EQ-3 AG
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] running in production mode
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] will connect to your ccu at xxx.xxx.xxx.22
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] using xmprpc for communication with BidCos-RF
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] init RPC for BidCos-RF.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] local ip used : xxx.xxx.xxx.29. you may change that with local_ip parameter in config
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] using xmprpc for communication with BidCos-Wired
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] init RPC for BidCos-Wired.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] local ip used : xxx.xxx.xxx.29. you may change that with local_ip parameter in config
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] init RPC for HmIP-RF.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] local ip used : xxx.xxx.xxx.29. you may change that with local_ip parameter in config
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Fetching Homematic devices...
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Local cache is set to /root/.homebridge/ccu.json
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] RPC server for interface BidCos-RF. is listening on port 9090.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Creating Local HTTP Client for CCU RPC Events
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] CCU RPC Init Call on port 2001 for interface BidCos-RF.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] RPC server for interface BidCos-Wired. is listening on port 9091.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Creating Local HTTP Client for CCU RPC Events
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] CCU RPC Init Call on port 2000 for interface BidCos-Wired.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] RPC server for interface HmIP-RF. is listening on port 9092.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Creating Local HTTP Client for CCU RPC Events
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] CCU RPC Init Call on port 2010 for interface HmIP-RF.
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] if PONG is PONG CCU is alive
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] CCU Response for init at BidCos-Wired. with http://xxx.xxx.xxx.29:9091...Value (undefined) Error : (Error: Unknown XML-RPC tag 'TITLE'
    at Deserializer.onError (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:109:20)
    at Deserializer.onClosetag (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:206:14)
    at SAXStream.emit (events.js:210:5)
    at SAXParser.me._parser.<computed> [as onclosetag] (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:220:15)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:325:33)
    at emitNode (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:330:3)
    at closeTag (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:547:5)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:958:29)
    at SAXStream.write (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:202:16)
    at IncomingMessage.ondata (_stream_readable.js:726:22))
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] CCU Response for init at HmIP-RF. with http://xxx.xxx.xxx.29:9092...Value ("") Error : (null)
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] Method call params for 'system.listMethods': ["homebridge_BidCos-RF."] (null)
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] rpc <- listDevices on HmIP-RF. - Zero Reply (null)
[11/8/2019, 4:29:08 PM] [HomeMatic CCU2] rpc <- listDevices on BidCos-RF. - Zero Reply (null)
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] rpc <- newDevices on HmIP-RF. nobody is interested in newdevices ... (null)
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] CCU Response for init at BidCos-RF. with http://xxx.xxx.xxx.29:9090...Value ("") Error : (null)
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] CCU response on device query are 21448 bytes
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Load BuildIn Service Class HomeMaticHomeKitDimmerService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] service for HM-LC-Dim1PWM-CV:DIMMER is HomeMaticHomeKitDimmerService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Check config for HM-LC-Dim1PWM-CV:DIMMER
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] adding new address BidCos-RF.MEQ0874479:1.LEVEL for processing events at Deckenlicht
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] RPC getValue Call for MEQ0874479:1 LEVEL
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Load BuildIn Service Class HomeMaticHomeKitDimmerService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] service for HM-LC-Dim1TPBU-FM:DIMMER is HomeMaticHomeKitDimmerService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Check config for HM-LC-Dim1TPBU-FM:DIMMER
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] adding new address BidCos-RF.NEQ1801906:1.LEVEL for processing events at Esstisch
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] RPC getValue Call for NEQ1801906:1 LEVEL
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Programs : []
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Load BuildIn Service Class HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] service for VARIABLE:VARIABLE is HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Check config for VARIABLE:VARIABLE
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Load BuildIn Service Class HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] service for VARIABLE:VARIABLE is HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Check config for VARIABLE:VARIABLE
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Load BuildIn Service Class HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] service for VARIABLE:VARIABLE is HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Check config for VARIABLE:VARIABLE
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Load BuildIn Service Class HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] service for VARIABLE:VARIABLE is HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Check config for VARIABLE:VARIABLE
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Load BuildIn Service Class HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] service for VARIABLE:VARIABLE is HomeMaticHomeKitVariableService
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Check config for VARIABLE:VARIABLE
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Number of mapped devices : 7
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Initializing platform accessory 'Deckenlicht'...
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Initializing platform accessory 'Esstisch'...
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Initializing platform accessory 'Anwesend'...
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Initializing platform accessory 'Abwesend'...
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Initializing platform accessory 'Fernsehen'...
[11/8/2019, 4:29:10 PM] [HomeMatic CCU2] Initializing platform accessory 'Essen'...
Setup Payload:
X-HM://xxxxxxxxxxxxxxxxxx
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ xxx-xx-xxx │
    └────────────┘

[11/8/2019, 4:29:11 PM] Homebridge is running on port 51826.
[11/8/2019, 4:29:11 PM] [HomeMatic CCU2] rpc <- newDevices on BidCos-RF. nobody is interested in newdevices ... (null)
[11/8/2019, 4:29:11 PM] [HomeMatic CCU2] Variable Anwesend set to false
[11/8/2019, 4:29:11 PM] [HomeMatic CCU2] Variable Abwesend set to false
[11/8/2019, 4:29:11 PM] [HomeMatic CCU2] Variable Fernsehen set to false
 [11/8/2019, 4:29:11 PM] [HomeMatic CCU2] Variable Essen set to false
[11/8/2019, 4:29:11 PM] [HomeMatic CCU2] will cache ccu response to /root/.homebridge/ccu.json
[11/8/2019, 4:29:11 PM] [HomeMatic CCU2] RPC getValue (MEQ0874479:1 LEVEL) Response 0.8  | Errors: null
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] rpc <- system.multicall on BidCos-RF. (null)
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.MEQ0874479:1 LEVEL with value 0.8
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Deckenlicht found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] rpc <- system.multicall on BidCos-RF. (null)
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.MEQ0874479:1 WORKING with value false
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Deckenlicht found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.MEQ0874479:1 DIRECTION with value 0
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Deckenlicht found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.MEQ0874479:1 ERROR_REDUCED with value false
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Deckenlicht found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.MEQ0874479:1 ERROR_OVERHEAT with value false
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Deckenlicht found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] rpc <- system.multicall on BidCos-RF. (null)
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.NEQ1801906:1 LEVEL with value 0
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Esstisch found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC getValue (NEQ1801906:1 LEVEL) Response 0  | Errors: null
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] rpc <- system.multicall on BidCos-RF. (null)
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.NEQ1801906:1 WORKING with value false
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Esstisch found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.NEQ1801906:1 DIRECTION with value 0
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Esstisch found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.NEQ1801906:1 ERROR_REDUCED with value false
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Esstisch found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.NEQ1801906:1 ERROR_OVERLOAD with value false
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Esstisch found -> Send Event
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] RPC event for BidCos-RF.NEQ1801906:1 ERROR_OVERHEAT with value false
[11/8/2019, 4:29:12 PM] [HomeMatic CCU2] Accessory Esstisch found -> Send Event
[11/8/2019, 4:29:17 PM] [HomeMatic CCU2] NPM 0.0.109 vs Local 0.0.109
`

**Comment by mnni** [comment]
Hi, I might have a similar issue:

I'm using RaspberryMatic 3.49.17 since a few days and its working as expected. I'm using homebridge version 0.4.50 with config-ui-x in a freebsd jail. Homebridge is working fine so far as well as rasperrymatic.

But the homebridge-homematic plugin cannot access the CCU:
```
[1/28/2020, 12:48:17 PM] Homebridge is running on port 51826.
[1/28/2020, 12:48:17 PM] [HomeMatic RasPi] CCU Response for init at BidCos-RF. with http://10.0.0.10:9090...Value (undefined) Error : (Error: Unknown XML-RPC tag 'TITLE'
    at Deserializer.onError (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:109:20)
    at Deserializer.onClosetag (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:202:14)
    at SAXStream.emit (events.js:219:5)
    at SAXParser.me._parser.<computed> [as onclosetag] (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:220:15)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)
    at emitNode (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:330:3)
    at closeTag (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:547:5)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:958:29)
    at SAXStream.write (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:202:16)
    at IncomingMessage.ondata (_stream_readable.js:753:22))
[1/28/2020, 12:48:17 PM] [HomeMatic RasPi] CCU Response for init at VirtualDevices. with http://10.0.0.10:9093...Value (undefined) Error : (Error: Unknown XML-RPC tag 'TITLE'
    at Deserializer.onError (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:109:20)
    at Deserializer.onClosetag (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:202:14)
    at SAXStream.emit (events.js:219:5)
    at SAXParser.me._parser.<computed> [as onclosetag] (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:220:15)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)
    at emitNode (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:330:3)
    at closeTag (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:547:5)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:958:29)
    at SAXStream.write (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:202:16)
    at IncomingMessage.ondata (_stream_readable.js:753:22))
[1/28/2020, 12:48:17 PM] [HomeMatic RasPi] CCU Response for init at HmIP-RF. with http://10.0.0.10:9092...Value (undefined) Error : (Error: Unknown XML-RPC tag 'TITLE'
    at Deserializer.onError (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:109:20)
    at Deserializer.onClosetag (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:202:14)
    at SAXStream.emit (events.js:219:5)
    at SAXParser.me._parser.<computed> [as onclosetag] (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:220:15)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)
    at emitNode (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:330:3)
    at closeTag (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:547:5)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:958:29)
    at SAXStream.write (/usr/local/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:202:16)
    at IncomingMessage.ondata (_stream_readable.js:753:22))
[1/28/2020, 12:48:18 PM] [HomeMatic RasPi] NPM 0.0.205 vs Local 0.0.205
...
[1/28/2020, 12:33:01 PM] [HomeMatic RasPi] Unable to parse live ccu data. Will try cache if there is one. If you want to know what, start homebridge in debug mode -> DEBUG=* homebridge -D
[1/28/2020, 12:33:01 PM] [HomeMatic RasPi] Unable to load cached ccu data. giving up
```

As above the exception text `Unknown XML-RPC tag 'TITLE'` seems to be the problem. I didn't see any changes in the shipped homematic-XML RPC API for a long time? I'm a new user, so maybe I missed something here, but couldn't find any help so far...

Thank you

**Comment by thkl** [comment]
Seems like the xmlrpc and rega did not respond as expected, maybe you take a look into your ccu firewall settings. The homebridge MUST have access to the xmlrpc api and the logic layer.
