### ISSUE TITLE
Problem beim Starten der Homebridge

### ISSUE THREAD

**Issue by FreddyHamburg** [thkl/homebridge-homematic#52]
Hallo,

ich habe folgendes Problem.
Nachdem ich den Raspberry mit der Homebridge neu aufgesetzt habe, erhalte ich beim Starten folgende Fehlermeldung:

[10/18/2016, 2:51:58 PM] [HomeMatic CCU] Initializing platform accessory 'HM-PB-2-WM CUX2801003:1'...
[10/18/2016, 2:51:58 PM] [HomeMatic CCU] Initializing platform accessory 'Whz-Dim-Deckenleuchte'...
[10/18/2016, 2:51:58 PM] [HomeMatic CCU] Initializing platform accessory 'Whz-Dim-StehLampe'...
[10/18/2016, 2:51:58 PM] [HomeMatic CCU] Initializing platform accessory 'Whz-Schalt-Wohnwand'...
[10/18/2016, 2:51:58 PM] [HomeMatic CCU] Number of mapped devices : 4
[10/18/2016, 2:51:59 PM] [HomeMatic CCU] NPM 0.0.45 vs Local 0.0.45
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:231
     if ((that.isWorking == true) && (value==false)) {
                                      ^

ReferenceError: value is not defined
    at HomeMaticHomeKitDimmerService.HomeKitGenericService.event (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:231:39)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:103:20
    at Array.map (native)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:101:38)
    at emitThree (events.js:97:13)
    at Server.emit (events.js:175:7)
    at /usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/server.js:42:14
    at callback (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:65:7)
    at Deserializer.onDone (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at emitNone (events.js:67:13)
    at SAXStream.emit (events.js:166:7)
    at Object.SAXStream._parser.onend (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:363:3)
    at Object.SAXParser.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:209:16)

Wenn ich die Kanäle auf der Homematic aus dem Gewerk entferne, startet die Homebridge problemlos. Sobald auch nur ein Kanal wieder hinzugefügt wird, streikt die Bridge wieder.

Die json.config ist die gleiche, die ich vor der Neuinstallation ohne Probleme funktioniert hat. Hier noch die Config:
{
		"platform": "HomeMatic",
		"name": "HomeMatic CCU",
		"ccu_ip": "192.168.1.110",
		"filter_device": [],
		"filter_channel": [],
		"outlets": [],
		"doors": [],
		"programs": [],
		"subsection": "Siri"
	},

Hat jemand eine Idee dazu?

Vielen Dank im Voraus.

**Comment by FreddyHamburg** [comment]
Das gleiche Problem tritt bei der Version 0.0.44 aus. Ich bin jetzt auf die Version 0.0.43 zurück gegangen, da habe ich keine Probleme

**Comment by bpohvoodoo** [comment]
Ich bekomme die hier:

/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitRaindetectorService.js:27
    var rain= new Service["IsRainingService"](this.name);
              ^

TypeError: Service.IsRainingService is not a constructor
    at HomeMaticHomeKitRaindetectorService.createDeviceService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitRaindetectorService.js:27:15)
    at HomeMaticHomeKitRaindetectorService.HomeKitGenericService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:51:8)
    at new HomeMaticHomeKitRaindetectorService (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitRaindetectorService.js:8:48)
    at HomeMaticChannelLoader.loadChannelService (/usr/lib/node_modules/homebridge-homematic/HomeMaticChannelLoader.js:43:20)
    at /usr/lib/node_modules/homebridge-homematic/index.js:253:33
    at Array.map (native)
    at /usr/lib/node_modules/homebridge-homematic/index.js:212:32
    at Array.map (native)
    at /usr/lib/node_modules/homebridge-homematic/index.js:197:25
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:41:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by thkl** [comment]
Ich schau mir das mal an.

**Comment by thkl** [comment]
geht in 0.0.46 wieder

**Comment by thkl** [comment]
Nachtrag @bpohvoodoo  Das RainDetector Problem wird erst in 0.0.47 drin sein. die Github Version hier kennt den fix schon

**Comment by bpohvoodoo** [comment]
Hi habe die Version von Github genommen jetzt hab ich das:
/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitRaind                                                                                                                               etectorService.js:35
        var servUUID = uuid.generate('HomeMatic:customchar:IsRainingService');
                           ^

TypeError: Cannot read property 'generate' of undefined
    at new Service.IsRainingService (/usr/lib/node_modules/homebridge-homematic/                                                                                                                               ChannelServices/HomeMaticHomeKitRaindetectorService.js:35:23)
    at HomeMaticHomeKitRaindetectorService.createDeviceService (/usr/lib/node_mo                                                                                                                               dules/homebridge-homematic/ChannelServices/HomeMaticHomeKitRaindetectorService.j                                                                                                                               s:50:15)
    at HomeMaticHomeKitRaindetectorService.HomeKitGenericService (/usr/lib/node_                                                                                                                               modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:51:8)
    at new HomeMaticHomeKitRaindetectorService (/usr/lib/node_modules/homebridge                                                                                                                               -homematic/ChannelServices/HomeMaticHomeKitRaindetectorService.js:8:48)
    at HomeMaticChannelLoader.loadChannelService (/usr/lib/node_modules/homebrid                                                                                                                               ge-homematic/HomeMaticChannelLoader.js:43:20)
    at /usr/lib/node_modules/homebridge-homematic/index.js:253:33
    at Array.map (native)
    at /usr/lib/node_modules/homebridge-homematic/index.js:212:32
    at Array.map (native)
    at /usr/lib/node_modules/homebridge-homematic/index.js:197:25
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/H                                                                                                                               omeMaticRegaRequest.js:41:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by thkl** [comment]
sorry hab vergessen ein file einzuchecken .. jetzt aber

**Comment by FreddyHamburg** [comment]
Schon mal vielen Dank für deine Mühe.
Leider erhalte ich jetzt aber folgende Fehlermeldung:

[10/25/2016, 7:47:58 PM] [HomeMatic CCU] Number of mapped devices : 4
/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:237
       that.isWorking = value;
                        ^

ReferenceError: value is not defined
    at HomeMaticHomeKitDimmerService.HomeKitGenericService.event (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:237:25)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:103:20
    at Array.map (native)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:101:38)
    at emitThree (events.js:97:13)
    at Server.emit (events.js:175:7)
    at /usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/server.js:42:14
    at callback (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:65:7)
    at Deserializer.onDone (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at emitNone (events.js:67:13)
    at SAXStream.emit (events.js:166:7)
    at Object.SAXStream._parser.onend (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:363:3)
    at Object.SAXParser.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/local/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/node_modules/sax/lib/sax.js:209:16)

**Comment by thkl** [comment]
ach mist, ich sollte sowas nicht nebenbei fixen. Ist erledigt. HomeKitGenericService.js muss ausgetauscht werden.

Wenn das geht mach ich dann ein 0.0.47 draus .

**Comment by bpohvoodoo** [comment]
Also laufen tu es erstmal. Danke.

in der channel_config.json fehlte für mich noch
	{
	   "type": "HM-WDS100-C6-O:WEATHER",
	   "service": "HomeMaticHomeKitWeatherStationService"
	},

in der HomeMaticHomeKitWeatherStationService.js
scheint nach den Characteristics noch das zu fehlen.

  Service.IsRainingService = function(displayName, subtype) {
  	var servUUID = uuid.generate('HomeMatic:customchar:IsRainingService');
  	Service.call(this, displayName, servUUID, subtype);
	this.addCharacteristic(Characteristic.IsRainingCharacteristic);
  };
  
  util.inherits(Service.IsRainingService, Service);

**Comment by thkl** [comment]
Die persönlichen Änderungen in der Type zu Service kann in der config.json gemacht werden. Dort wird sie beim Update nicht überschrieben.  Wie das geht steht in der Readme hier auf der ersten Seite.

**Comment by bpohvoodoo** [comment]
Ja, hab ich gesehen, aber ich dachte mir, wenn die Version 2 eh fest drin ist kann die V1 auch rein ;-)

**Comment by FreddyHamburg** [comment]
Läuft nach Austausch der HomeKitGenericService.js wieder problemlos. Vielen Dank!
