### ISSUE TITLE
Homebridge startet nicht mehr

### ISSUE THREAD

**Issue by bpohvoodoo** [thkl/homebridge-homematic#561]
Hallo,

ich wollte heute mal die neue Version ausprobieren. (Master Branch von heute)
Leider crasht die sofort.
Hier das Log

[2/29/2020, 3:30:30 PM] TypeError: Cannot read property 'Characteristic' of undefined
    at HomeMaticHomeKitMotionDetectorService.createDeviceService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorService.js:44:42)
    at new HomeKitGenericService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:117:12)
    at new HomeMaticHomeKitMotionDetectorService (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitMotionDetectorService.js:8:1)
    at HomeMaticServiceClassLoader.loadChannelService (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticServiceClassLoader.js:141:29)
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:278:36
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:213:27
    at Array.map (<anonymous>)
    at HomeMaticPlatform.updateAccesories (/usr/local/lib/node_modules/homebridge-homematic/index.js:203:32)
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:187:14
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticCCU.js:199:9
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by bpohvoodoo** [comment]
Hat sich erledigt. Warum auch immer
