### ISSUE TITLE
Nach Update von 45 auf 49 unbekannter Fehler

### ISSUE THREAD

**Issue by gitfisch** [thkl/homebridge-homematic#58]
Hallo zusammen, nach dem Update auf 49 bekomme ich die unten aufgeführte fehlermeldung. Leider werd ich aus dieser Fehlermeldung nicht schlau.
Bitte um Hilfe 
Gitfisch

[10/30/2016, 12:29:39 PM] Homebridge is running on port 51826.
[10/30/2016, 12:29:39 PM] [HomeMatic CCU] Number of mapped devices : 65
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_mod                                       ules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap                                       -nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_mod                                       ules/hap-nodejs/lib/Accessory.js:480:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:92:                                       16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:                                       351:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/o                                       nce.js:15:19
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:296:9
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homem                                       atic/HomeMaticRegaRequest.js:41:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)

**Comment by bpohvoodoo** [comment]
hmm, entweder ist der Port von was anderem belegt, oder homebridge läuft schon.
versuch mal
sudo /etc/init.d/homebridge restart

**Comment by thkl** [comment]
Die Fehlermeldung kommt wenn die Bridge schon läuft ...
