### ISSUE TITLE
Version v0.1.222 nicht aktualisieren!

### ISSUE THREAD

**Issue by pbksol** [thkl/homebridge-homematic#591]
Kleine Warnung… Wenn ihr die Version 0.1.222 zur Installation angeboten bekommt… Nicht installieren. Diese Version hinterlässt eine Art Blutbad in Eurem System.

Nach der Installation heute (installiert war die Vorgänger-Version, die über NPM verteilt wurde) ist fast alles, was Homematic betrifft kaputt.

- Alle Raumzuordungen fehlten
- Alle Namen waren auf die von Homematic übermittelten Defaults zurückgesetzt und damit gehen auch alle HomeKit-Automatisierungen kaputt
- Statusänderungen werden nicht mehr übermittelt (Fenster auf/zu) etc.
- Die Outlet-Definition wird ignoriert, Variablen werden aber noch übergeben

Ein Restore auf die 0.0.219 änderte nichts an dem Zustand.

Falls Ihr also heute noch was anderes vor habt, lasst die Aktualisierung und wartet, dass es wieder eine funktionierende Version gibt.

Und ja, es betraf ausschließlich das Homematic-Plugin. Alle anderen Komponenten funktionieren tadellos.

**Comment by thkl** [comment]
Ja die 222 hat leider kein Beta Tag und wurde als normales Update gepusht. Die kann ich leider nicht mehr zurücknehmen. 

Die Beta 229 fixt das.

**Comment by jk-andersen** [comment]
Bei mir ist leider auch alles Kaputt.
Wann kommt die 229? Das Plugin restartet permanent.

**Comment by thkl** [comment]
Ich denke mal irgendwann heute Abend

**Comment by fighterzg6** [comment]
hatte die beta 0.1.229 auch probiert, nicht wirklich anders

**Comment by thkl** [comment]
Gibt es irgendwelche Error Meldungen im Log ?

**Comment by jk-andersen** [comment]
`[2020-4-20 1:22:18 PM] TypeError: Cannot read property 'setValue' of undefined
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermostatServiceIP.js:19:63
    at self.remoteGetValue.value (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:460:11)
    at self.ccuManager.getValue.newValue (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:688:13)
    at HomeMaticCCU.getValueRega (/usr/lib/node_modules/homebridge-homematic/HomeMaticCCU.js:110:9)
    at HomeMaticCCU.getValue (/usr/lib/node_modules/homebridge-homematic/HomeMaticCCU.js:135:12)
    at HomeMaticHomeKitIPThermostatService.remoteGetValue (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:661:25)
    at HomeMaticHomeKitIPThermostatService.query (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:458:12)
    at Characteristic.CurrentHeatingCoolingState.<anonymous> (/usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitThermostatServiceIP.js:14:14)
    at Characteristic.CurrentHeatingCoolingState.emit (events.js:198:13)
    at Characteristic.CurrentHeatingCoolingState.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
[2020-4-20 1:22:18 PM] Got SIGTERM, shutting down Homebridge...
[2020-4-20 1:22:18 PM] [CCu3] [RPC] disconnecting all interfaces
[2020-4-20 1:22:18 PM] [CCu3] [RPC] Removing Event Server for Interface BidCos-RF.
[2020-4-20 1:22:18 PM] [CCu3] [RPC] Removing Event Server for Interface HmIP-RF.
[2020-4-20 1:22:18 PM] [CCu3] [RPC] Removing Event Server for Interface CUxD.
[2020-4-20 1:22:18 PM] [CCu3] [RPC] Error while removing eventserver on if CUxD. Error : Error: Unexpected end
Line: 109
Column: 0
Char: 
[2020-4-20 1:22:23 PM] [HomeMatic Configuration Service] [Config] Shutdown Configuration Service
[2020-4-20 1:22:23 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null`

**Comment by thkl** [comment]
OK das fixe ich ...

**Comment by fighterzg6** [comment]
Kann man den Port für die neue Konfigurationsseite ändern? (Da 3 Instanzen und 3 verschiedene ccu‘s)?

**Comment by thkl** [comment]
Ja config Key ist configServerPort

**Comment by thkl** [comment]
So, Version 0.1.231 ist ein Rollback auf die 219 ...

**Comment by pbksol** [comment]
> So, Version 0.1.231 ist ein Rollback auf die 219 ...

Die wirft dann aber wieder alle schon wieder auf die richtigen Räume verteilten Geräte und deren Namen durcheinander. Das Rollback auf die 219 hatte ich heute Morgen versucht nachdem ich schon alles wieder in die Räume verschoben hatten und da war dann ja wieder Chaos – ich rechne ja zuerst immer mit eigenem Versagen bevor ich die Schuld woanders suche…

Und weil sich dann die Namen wieder ändern sind auch alle Automatisierungen wieder kaputt.

Bleibt es noch bei der Freigabe der korrigierten Version im Laufe des Tages?

**Comment by thkl** [comment]
Wie sich rausstellt erzeugt die Änderung auf das dynamische Erzeugen der Geräte eine neue UUID. Damit kommt das Problem mit den kaputten Räumen und Automatisierungen.

Daher das Rollback und die Beibehaltung der Statischen Initialisierung wie in 219. Dummerweise hätte die 222 nie veröffentlicht werden sollen, ich hatte da das beta tag vergessen.

**Comment by MaLi812** [comment]
Ich habe ebenfalls v0.1.222 installiert. Räume, Benennungen, Automatisierungen alles futsch. Habe das alles wieder eingegeben und jetzt läuft v0.1.222 eigentlich sehr gut bei mir. Soll ich trotzdem den Rollback mit Version 0.1.231 machen, oder lohnt es sich zu warten? 

Danke und viele Grüße
MaLi

**Comment by thkl** [comment]
Ja sorry aber die 222 und nachfolgende haben noch zu viele Fehler, sollten eigentlich so nie rausfallen ... es wird definitiv zurück zu 219 (231) gehen.

**Comment by MaLi812** [comment]
Alles klar. Danke. Shit happens. 
Dann wieder zurück... gibt schlimmeres.

**Comment by shinzan111** [comment]
Hallo, 
klappt das denn nun mit den Cuxd Statusmeldungen?  Bei mir haben die immer wieder den falschen Status. Gleiches übrigens bei HM IP Bewegungsmeldern … deren Status bleibt gänzlich falsch

**Comment by thkl** [comment]
Nein die sind in der 219/231 noch nicht wieder drin ... aber mach ich ... Problem ist das CuxD wohl nur binrpc kann. ¯\_(ツ)_/¯

**Comment by Soilman82** [comment]
Ich war noch auf der 219 und habe ein Update auf die 231 gemacht. Alles dazwischen ist zum Glück an mir vorüber gegangen. :-) Die 231 funktioniert auf jeden Fall wie gewohnt.

**Comment by thkl** [comment]
231 ist 219 nur mit einer höheren Nummer damit 222 überschrieben wird. Man kann im npm leider eine Version nicht löschen wenn die älter als 72h ist.

**Comment by Soilman82** [comment]
Wollte damit eigentlich auch nur bestätigen, dass der Rollback erfolgreich war. 😄 Einziger Punkt, der mir noch aufgefallen war: Im UI wurden mir die Release Notes von der 220 angezeigt.

**Comment by thkl** [comment]
Ja die kommen aus dem GitHub Release
