### ISSUE TITLE
No Devices - please help

### ISSUE THREAD

**Issue by colseven** [thkl/homebridge-homematic#654]
After install no Devices just this Error.

`Started Node.js HomeKit Server.
[19/02/2021, 17:39:22] Loaded config.json with 0 accessories and 2 platforms.
[19/02/2021, 17:39:22] ---
[19/02/2021, 17:39:23] Loaded plugin: homebridge-config-ui-x@4.39.0
[19/02/2021, 17:39:23] Registering platform 'homebridge-config-ui-x.config'
[19/02/2021, 17:39:23] ---
[19/02/2021, 17:39:23] Loaded plugin: homebridge-homematic@0.1.231
[19/02/2021, 17:39:23] Registering platform 'homebridge-homematic.HomeMatic'
[19/02/2021, 17:39:23] ---
[19/02/2021, 17:39:23] Loading 2 platforms...
[19/02/2021, 17:39:23] [Config] Initializing config platform...
[19/02/2021, 17:39:23] [Config] Spawning homebridge-config-ui-x with PID 1467
[19/02/2021, 17:39:23] [HomeMatic CCU] Initializing HomeMatic platform...
[19/02/2021, 17:39:23] [HomeMatic CCU] [Core] merging configurations
[19/02/2021, 17:39:23] [HomeMatic CCU] Homematic Plugin Version 0.1.231
[19/02/2021, 17:39:23] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[19/02/2021, 17:39:23] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[19/02/2021, 17:39:23] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[19/02/2021, 17:39:23] [HomeMatic CCU] running in production mode
[19/02/2021, 17:39:23] [HomeMatic CCU] will connect to your ccu at 192.168.178.21
[19/02/2021, 17:39:23] [HomeMatic CCU] IMPORTANT !! Starting this version, your homematic custom configuration is located in /var/homebridge/homematic_config.json
[19/02/2021, 17:39:23] [HomeMatic CCU] [RPC] using xmprpc for communication with BidCos-RF
[19/02/2021, 17:39:23] [HomeMatic CCU] init RPC for BidCos-RF.
[19/02/2021, 17:39:23] [HomeMatic CCU] [RPC] local ip used : 192.168.178.84. you may change that with local_ip parameter in config
[19/02/2021, 17:39:23] [HomeMatic CCU] init RPC for VirtualDevices.
[19/02/2021, 17:39:23] [HomeMatic CCU] [RPC] local ip used : 192.168.178.84. you may change that with local_ip parameter in config
[19/02/2021, 17:39:23] [HomeMatic CCU] [RPC] server for interface BidCos-RF. is listening on port 8082.
[19/02/2021, 17:39:23] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[19/02/2021, 17:39:23] RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received 80823.
    at validatePort (internal/validators.js:211:11)
    at Server.listen (net.js:1444:5)
    at HomeMaticRPC.isPortTaken (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:336:8)
    at HomeMaticRPC.init (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:106:8)
    at new HomeMaticPlatform (/usr/local/lib/node_modules/homebridge-homematic/index.js:113:25)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
[19/02/2021, 17:39:23] Got SIGTERM, shutting down Homebridge...
[19/02/2021, 17:39:23] [HomeMatic CCU] if  is PONG CCU is alive
Stopping Node.js HomeKit Server...
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
Stopped Node.js HomeKit Server.
homebridge.service: Found left-over process 1467 (node) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started Node.js HomeKit Server.`

**Comment by JensBonse** [comment]
You defined the port to be 80823.
Ports can only be in this range >= 0 and < 65536.

**Comment by colseven** [comment]
How can i change the Port?

**Comment by JensBonse** [comment]
Check in the settings of homebridge-homematic.
There you should find 80823 and just change it.

**Comment by colseven** [comment]
In setting i can't find the Port, and in the config there is noting.

        {
            "platform": "HomeMatic",
            "name": "HomeMatic CCU",
            "ccu_ip": "192.168.178.76",
            "subsection": "Homekit"
        },

**Comment by thkl** [comment]
please take a look into the homematic config file named hoematic_config.json

**Comment by colseven** [comment]
i add virtual_port then homebridge starts but no divices because no live data, what can i do? Unable to parse live ccu data.

[21/02/2021, 10:55:48] Loaded config.json with 0 accessories and 3 platforms.
[21/02/2021, 10:55:49] Loaded 0 cached accessories from cachedAccessories.
[21/02/2021, 10:55:49] ---
[21/02/2021, 10:55:52] Loaded plugin: homebridge-alexa@0.5.26
[21/02/2021, 10:55:52] Registering platform 'homebridge-alexa.Alexa'
[21/02/2021, 10:55:52] ---
[21/02/2021, 10:55:52] Loaded plugin: homebridge-config-ui-x@4.39.0
[21/02/2021, 10:55:52] Registering platform 'homebridge-config-ui-x.config'
[21/02/2021, 10:55:52] ---
[21/02/2021, 10:55:52] Loaded plugin: homebridge-homematic@0.1.231
[21/02/2021, 10:55:52] Registering platform 'homebridge-homematic.HomeMatic'
[21/02/2021, 10:55:52] ---
[21/02/2021, 10:55:52] Loading 3 platforms...
[21/02/2021, 10:55:52] [Config] Initializing config platform...
[21/02/2021, 10:55:52] [Config] Spawning homebridge-config-ui-x with PID 1769
[21/02/2021, 10:55:52] [Alexa] Initializing Alexa platform...
[21/02/2021, 10:55:52] [Alexa] Missing username and password
[21/02/2021, 10:55:52] [Alexa] homebridge-alexa v0.5.26, node v14.15.5, homebridge v1.3.0
[21/02/2021, 10:55:52] Initializing platform accessory 'Alexa'...
[21/02/2021, 10:55:52] [HomeMatic CCU] Initializing HomeMatic platform...
[21/02/2021, 10:55:52] [HomeMatic CCU] [Core] merging configurations
[21/02/2021, 10:55:52] [HomeMatic CCU] Homematic Plugin Version 0.1.231
[21/02/2021, 10:55:52] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[21/02/2021, 10:55:52] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[21/02/2021, 10:55:52] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[21/02/2021, 10:55:52] [HomeMatic CCU] running in production mode
[21/02/2021, 10:55:52] [HomeMatic CCU] will connect to your ccu at 192.168.178.21
[21/02/2021, 10:55:52] [HomeMatic CCU] IMPORTANT !! Starting this version, your homematic custom configuration is located in /var/homebridge/homematic_config.json
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] using xmprpc for communication with BidCos-RF
[21/02/2021, 10:55:52] [HomeMatic CCU] init RPC for BidCos-RF.
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] local ip used : 192.168.178.87. you may change that with local_ip parameter in config
[21/02/2021, 10:55:52] [HomeMatic CCU] init RPC for VirtualDevices.
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] local ip used : 192.168.178.87. you may change that with local_ip parameter in config
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] using xmprpc for communication with BidCos-Wired
[21/02/2021, 10:55:52] [HomeMatic CCU] init RPC for BidCos-Wired.
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] local ip used : 192.168.178.87. you may change that with local_ip parameter in config
[21/02/2021, 10:55:52] [HomeMatic CCU] init RPC for HmIP-RF.
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] local ip used : 192.168.178.87. you may change that with local_ip parameter in config
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] server for interface BidCos-RF. is listening on port 9090.
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] server for interface VirtualDevices. is listening on port 9093.
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] server for interface BidCos-Wired. is listening on port 9091.
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] server for interface HmIP-RF. is listening on port 9092.
[21/02/2021, 10:55:52] [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
[21/02/2021, 10:55:52] [HomeMatic CCU] if  is PONG CCU is alive
[21/02/2021, 10:55:52] [HomeMatic CCU] [Core] Unable to parse live ccu data. Will try cache if there is one. If you want to know what, start homebridge in debug mode -> DEBUG=* homebridge -D
[21/02/2021, 10:55:52] [HomeMatic CCU] [Core] ok local cache is set to /var/homebridge/ccu.json
[21/02/2021, 10:55:53] [HomeMatic CCU] [Core] Unable to load cached ccu data. giving up
Preparing Advertiser for 'Homebridge CAD8' using bonjour-hap backend!
Setup Payload:

**Comment by JensBonse** [comment]
Is the IP of your CCU correct?
Are the ports open on CCU?

**Comment by colseven** [comment]
Yes and yes

**Comment by thkl** [comment]
there is no response from the logic interface (rega) of your ccu : 

```
[21/02/2021, 10:55:52] [HomeMatic CCU] if is PONG CCU is alive
```

The correct message should be if PONG is PONG CCU is alive
This function will not use any local server it just sends out a request to port 8181 of your ccu and will process the result.
Please make sure that your ccu firewall is setup correctly. 

You may try this in a browser: 
http://192.168.178.21:8181/tclrega.exe

should end up in something like that
```
<xml>
<exec>/tclrega.exe</exec>
<sessionId/>
<httpUserAgent>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
</httpUserAgent>
</xml>
???

**Comment by colseven** [comment]
Problem gelöst!
In der CCU3 war unter Sicherheit die Authentifizierung aktiviert :( Jetzt läuft alles.

**Comment by thkl** [comment]
Ich schau mal, das ich den Plugin eine Option für User Passwort mitgebe. Dann kann die Authentifizierung eingeschalten werden.
