### ISSUE TITLE
HMIP Broll kann nicht hinzugefügt werden

### ISSUE THREAD

**Issue by Ritschi87** [thkl/homebridge-homematic#656]
Hallo zusammen,

ich habe heute meine Homebridge neu aufgesetzt. Installation und Konfiguration lief ohne Probleme durch.

Plugin für die Homematic ist installiert und Konfiguriert. Alle Homematic-Geräte sind in der Homebridge zu sehen und zu steuern. 

Allerdings machen meine Rolladen HMIP-Broll Probleme. nachdem ich diese Hinzugefügt habe und den Homebridge-Service neu starte bekomme ich folgenden fehler:

Error: characteristic value NaN is not contained in valid values array!
    at PositionState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2028:15)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:71:13
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:410:13
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:597:9
    at /usr/local/lib/node_modules/homebridge-homematic/index.js:649:9
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:66:9
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
    at IncomingMessage.emit (events.js:327:22)

Bei allen anderen Geräte funktioniert alles wie gewohnt. 

Kann mir jemand helfen? 

LG Andre

**Comment by thkl** [comment]
siehe #658 das sollte mit 0.2.224 erledigt sein
