### ISSUE TITLE
Homebridge 130 und NaN bei HomeMaticHomeKitBlindServiceIP.js

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/homebridge-homematic#657]
Ähnlich #634 bekomme ich die Meldung beim HomeMaticHomeKitBlindServiceIP.js

```
[20/02/2021, 21:47:24] Error: characteristic value NaN is not contained in valid values array!
    at PositionState.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2028:15)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:71:13
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:410:13
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:597:9
    at /usr/lib/node_modules/homebridge-homematic/index.js:649:9
    at /usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:66:9
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[20/02/2021, 21:47:24] Error: characteristic value NaN is not contained in valid values array!
    at PositionState.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2028:15)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1490:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:71:13
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:410:13
    at /usr/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:597:9
    at /usr/lib/node_modules/homebridge-homematic/index.js:649:9
    at /usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:66:9
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[20/02/2021, 21:47:25] [homebridge-homematic] This plugin generated a warni
```

**Comment by thkl** [comment]
siehe #658 (ist in 0.2.224 gelöst)
