### ISSUE TITLE
This plugin generated a warning from the characteristic....

### ISSUE THREAD

**Issue by votecc9** [thkl/homebridge-homematic#671]
hallo, 

auch bei mir seit letztem Update folgende Fehlermeldung 

This plugin generated a warning from the characteristic 'Sonnenscheindauer': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.

und

This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.

Homebridge V1.3.2
homebridge-homematic v0.2.226

Das System ist teilweise derart mit sich selbst beschäftigt, das von mir über IOS erstellt Kurzbefehle nicht mehr korrekt ausgeführt werden.
Die Kurzbefehle bestehen aus einer zeitlichen Abfolge (im Sekundenbereich) von Schaltzuständen der Aktoren. Die ersten zwei bis drei Schaltzustände werden erreicht (ist unterschiedlich), die weiteren Schaltzustände bleiben aus. 
 Debugfile ist angehängt.
[homebridge.log-4.txt](https://github.com/thkl/homebridge-homematic/files/6096657/homebridge.log-4.txt)

Eine Lösung des Problems wäre klasse.

Vielen Dank, Gruß Andreas

**To Reproduce**
1.  
2.  
3.  
4.  

**Actual behaviour**
A clear and concise description of what is actually happen.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by fighterzg6** [comment]
ich habe das gleiche Problem mit einem anderen Gerät
[2021-3-9 11:49:38] [homebridge-homematic] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[2021-3-9 11:49:38] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[2021-3-9 11:50:48] [homebridge-homematic] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[2021-3-9 11:50:48] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[2021-3-9 11:54:03] [homebridge-homematic] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[2021-3-9 11:54:03] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.

**Comment by MSlawik** [comment]
I have the same issue:
[3/16/2021, 07:30:19] [homebridge-homematic] This plugin generated a warning from the characteristic 'Smoke Detected': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

**Comment by inet-cologne** [comment]
The same Problem as @fighterzg6 here:

[homebridge-homematic] This plugin generated a **warning from the characteristic 'Current Position'**: characteristic was supplied **illegal value: number 10000 exceeded maximum of 100**. See https://git.io/JtMGR for more info.
See **stack trace** further on!

Raspberry4
pivCCU3 Ver.3.57.4
Homebridge 1.3.4
Homematic Plugin 0.2.226
HMIP-BROLL Firmware 1.8.20

**Stack trace:**
HmIP-RF.00111BE99987E0:4) -> Send Event with value 0
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] transformDatapoint LEVEL_STATUS
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] cache HmIP-RF.00111BE99987E0:4.LEVEL_STATUS (0)
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Cache] write 0 for HmIP-RF.00111BE99987E0:4.LEVEL_STATUS
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] datapointEvent 4.LEVEL_STATUS with 0 channel HmIP-RF.00111BE99987E0:4
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [RPC] event for HmIP-RF.00111BE99987E0:4.SECTION with value 4
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Cache] write 4 for HmIP-RF.00111BE99987E0:4.SECTION
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [RPC] Accessory (Rolladen Schlafzimmer rechts Aktor) found by channeladress (HmIP-RF.00111BE99987E0:4) -> Send Event with value 4
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] transformDatapoint SECTION
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] cache HmIP-RF.00111BE99987E0:4.SECTION (4)
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Cache] write 4 for HmIP-RF.00111BE99987E0:4.SECTION
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] datapointEvent 4.SECTION with 4 channel HmIP-RF.00111BE99987E0:4
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [RPC] event for HmIP-RF.00111BE99987E0:4.PROCESS with value 0
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Cache] write 0 for HmIP-RF.00111BE99987E0:4.PROCESS
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [RPC] Accessory (Rolladen Schlafzimmer rechts Aktor) found by channeladress (HmIP-RF.00111BE99987E0:4) -> Send Event with value 0
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] transformDatapoint PROCESS
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] cache HmIP-RF.00111BE99987E0:4.PROCESS (0)
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Cache] write 0 for HmIP-RF.00111BE99987E0:4.PROCESS
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] datapointEvent 4.PROCESS with 0 channel HmIP-RF.00111BE99987E0:4
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] transformDatapoint 4.LEVEL
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] remoteGetValue Intf:HmIP-RF, Adre:HmIP-RF.00111BE99987E0:4, Dp:LEVEL
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Core] getValue (HmIP-RF) HmIP-RF.00111BE99987E0:4.LEVEL
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Core] check cache HmIP-RF.00111BE99987E0:4.LEVEL
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Cache] hit on HmIP-RF.00111BE99987E0:4.LEVEL 100
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] got value for HmIP-RF.00111BE99987E0:4.LEVEL (Value:100)
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] Convert 10000 for 4.LEVEL is 10000
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] will cache 10000 for HmIP-RF.00111BE99987E0:4.LEVEL
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] cache HmIP-RF.00111BE99987E0:4.LEVEL (10000)
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Cache] write 10000 for HmIP-RF.00111BE99987E0:4.LEVEL
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Generic] run callback with 10000
**[19/03/2021, 13:56:34] [homebridge-homematic] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[19/03/2021, 13:56:34] [homebridge-homematic] Error:** 
    at CurrentPosition.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentPosition.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1950:16)
    at CurrentPosition.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:148:23
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:597:9
    at HomeMaticPlatform.getValue_rega (/usr/local/lib/node_modules/homebridge-homematic/index.js:645:7)
    at HomeMaticPlatform.getValue (/usr/local/lib/node_modules/homebridge-homematic/index.js:675:14)
    at HomeMaticHomeKitBlindServiceIP.remoteGetValue (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:568:19)
    at HomeMaticHomeKitBlindServiceIP.datapointEvent (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:147:10)
    at HomeMaticHomeKitBlindServiceIP.event (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:752:14)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:183:19
    at Array.map (<anonymous>)
    at HomeMaticRPC.handleEvent (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:179:36)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:146:22
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:145:22
[19/03/2021, 13:56:34] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[19/03/2021, 13:56:34] [homebridge-homematic] Error: 
    at TargetPosition.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetPosition.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1950:16)
    at TargetPosition.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:149:22
    at /usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:597:9
    at HomeMaticPlatform.getValue_rega (/usr/local/lib/node_modules/homebridge-homematic/index.js:645:7)
    at HomeMaticPlatform.getValue (/usr/local/lib/node_modules/homebridge-homematic/index.js:675:14)
    at HomeMaticHomeKitBlindServiceIP.remoteGetValue (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:568:19)
    at HomeMaticHomeKitBlindServiceIP.datapointEvent (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:147:10)
    at HomeMaticHomeKitBlindServiceIP.event (/usr/local/lib/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:752:14)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:183:19
    at Array.map (<anonymous>)
    at HomeMaticRPC.handleEvent (/usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:179:36)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:146:22
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:145:22
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [RPC] event for HmIP-RF.00111BE99987E0:4.ACTIVITY_STATE with value 3
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [Cache] write 3 for HmIP-RF.00111BE99987E0:4.ACTIVITY_STATE
[19/03/2021, 13:56:34] [inetHomeMatic VCCU3] [RPC] Accessory (Rolladen Schlafzimmer rechts Aktor) found by channeladress (HmIP-RF.00111BE99987E0:4) -> Send Event with value 3

**Just a guess:**
**Problem may be** in HomeKitGenericService.js at line 572. The value for remoteGetValue is multiplied by 100 which will probably not work for Blinds (HMIP-BROLL):
  remoteGetValue: function (dp, callback) {
    var that = this
    var tp = this.transformDatapoint(dp)
    var interf = this.intf
    this.log.debug('[Generic] remoteGetValue Intf:%s, Adre:%s, Dp:%s', interf, tp[0], tp[1])
    let dpadr = tp[0] + '.' + tp[1]
    that.platform.getValue(interf, tp[0], tp[1], function (newValue) {
      that.log.debug('[Generic] got value for %s (Value:%s)', dpadr, newValue)
      if ((newValue !== undefined) && (newValue !== null)) {
        if (tp[1] === 'LEVEL') {
          **newValue = newValue * 100**
        }

**Comment by preacha** [comment]
Same problem here. When can we expect a fix?
This means that no devices work for me with CCU3 3.57.4.

**Comment by Sungamm** [comment]
Good afternoon, same issue here. 

I set heating controler to "AUS" (off) and my log is full with "this plugin generated a warning from the characteristic... 

Only for the contoler they set to AUS. If I reduce to 10 degree, its fine. But maybe a fix for the summer mode (AUS / OFF) is possible, please?

`[11/05/2021, 14:58:15] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 10. See https://git.io/JtMGR for more info.`

**Comment by Sungamm** [comment]
No update until now. Is there a chance to fix the warning from log, please?

[27/05/2021, 18:53:42] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 10. See https://git.io/JtMGR for more info.

**Comment by mawe1202** [comment]
Hallo,

auch bei bei mir erscheint im Log ständig diese Meldung.
Gruß Mario

[6/23/2021, 4:31:30 PM] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 10. See https://git.io/JtMGR for more info.

**Comment by votecc9** [comment]
Habe meine CCU2 auf CCU3 geswapt. Keine Homebridge mehr nötig, funktioniert alles top. Ich denke, da tut sich auch nichts mehr hinsichtlich Bugfixing auf CCU2.

**Comment by inet-cologne** [comment]
@votecc9 
Was hat das mit CCU3 zu tun?
Kann die CCU3 mittlerweile nativ Homekit?

Ich habe meine Homematic Komponenten an meiner Raspberry Pi Zentrale pivCCU3 laufen und dort die (aktuelle) Version 3.57.5. Damit ich mit Siri meine Komponenten steuern kann habe ich Homebridge mit dem Homematic Plugin.

**Comment by snookerap** [comment]
> @votecc9
> Was hat das mit CCU3 zu tun?
> Kann die CCU3 mittlerweile nativ Homekit?
> 
> Ich habe meine Homematic Komponenten an meiner Raspberry Pi Zentrale pivCCU3 laufen und dort die (aktuelle) Version 3.57.5. Damit ich mit Siri meine Komponenten steuern kann habe ich Homebridge mit dem Homematic Plugin.

es gibt das passende Addon ebenfalls von @thkl -° HAP-Homematic

**Comment by CyberChris79** [comment]
Ich bekomme die gleiche Meldung.

**Comment by YogieAnamCara** [comment]
Here is the same for:

[21.7.2021, 11:25:06] [homebridge-homematic] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[21.7.2021, 11:25:06] [homebridge-homematic] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number 10000 exceeded maximum of 100. See https://git.io/JtMGR for more info.

**Comment by MSlawik** [comment]
You can fix the display in the Home App with this workaround:

Homematic BROLL (Rolladen) Aktor Wert korrigieren:

cd /homebridge/node_modules/homebridge-homematic/ChannelServices
pico HomeMaticHomeKitBlindServiceIP.js

Diese Zeile von 100 auf 10000 erhöhen:
 this.maxValueForOpen = this.getClazzConfigValue('maxValueForOpen', 10000)


This will not remove the log messages in Homebridge, but the shutters work properly.

**Comment by AlexanderSchmutz** [comment]
> > @votecc9
> > Was hat das mit CCU3 zu tun?
> > Kann die CCU3 mittlerweile nativ Homekit?
> > Ich habe meine Homematic Komponenten an meiner Raspberry Pi Zentrale pivCCU3 laufen und dort die (aktuelle) Version 3.57.5. Damit ich mit Siri meine Komponenten steuern kann habe ich Homebridge mit dem Homematic Plugin.
> 
> es gibt das passende Addon ebenfalls von @thkl -° HAP-Homematic

Läuft das Addon besser? Hier ist ja mit einem bugfixing leider nicht mehr zu rechnen…

**Comment by TiiFuchs** [comment]
> > > @votecc9
> > > Was hat das mit CCU3 zu tun?
> > > Kann die CCU3 mittlerweile nativ Homekit?
> > > Ich habe meine Homematic Komponenten an meiner Raspberry Pi Zentrale pivCCU3 laufen und dort die (aktuelle) Version 3.57.5. Damit ich mit Siri meine Komponenten steuern kann habe ich Homebridge mit dem Homematic Plugin.
> > 
> > 
> > es gibt das passende Addon ebenfalls von @thkl -° HAP-Homematic
> 
> Läuft das Addon besser? Hier ist ja mit einem bugfixing leider nicht mehr zu rechnen…

Gute Frage. Würde ich auch gerne wissen. Der Fehler geht echt auf die Nerven.

**Comment by mahrens61** [comment]
Wenn man sich an das Gui gewöhnt hat(funktioniert mittelprächtig), läuft hap-homematic ohne Probleme. Ich nutze es seit einem Jahr.
Auch neue Hom,ematic Devices sind integriert.

**Comment by snookerap** [comment]
Ich kann euch da bestens Home Assistant ans Herz legen.
Es gibt ein bestens gepflegtes Homematic Plugin und eine top Einbindung in homekit.

**Comment by 2slow4u** [comment]
> You can fix the display in the Home App with this workaround:
> 
> Homematic BROLL (Rolladen) Aktor Wert korrigieren:
> 
> cd /homebridge/node_modules/homebridge-homematic/ChannelServices pico HomeMaticHomeKitBlindServiceIP.js
> 
> Diese Zeile von 100 auf 10000 erhöhen: this.maxValueForOpen = this.getClazzConfigValue('maxValueForOpen', 10000)
> 
> This will not remove the log messages in Homebridge, but the shutters work properly.

This workaround did not work for me, as the issue keeps popping up.

Instead, I made a change inside HomeKitGenericService.js inside remoteGetValue Function:

`if (tp[1] === 'LEVEL') {
   if (newValue <= 1) {
     new Value = new Value * 100
    }
 }`
 
It seems that the initial setup required a value for level between 0 and 1, while the error above outlines, that the return value is in between 0 and 100. This fix at least helped in my setup solving the issue.

**Comment by CyberChris79** [comment]
Hello @2slow4u ,

thank you for your message
i will try your fix the next days and give you a feedback. 
How about updates?
I think you have to fix this after every update. 

Cheers
CyberChris79

**Comment by superbraz** [comment]
@2slow4u 

hast du damit die Fehlermeldung in der HB weg bekommen?

wenn ich 
if (tp[1] === 'LEVEL') { newValue = newValue * 100 }

mit dem von dir genannten
if (tp[1] === 'LEVEL') { if (newValue <= 1) { new Value = new Value * 100 } }

ersetze, kommt ein "Invalid left-hand side in assignment" und die HB startet ständig neu...

**Comment by jb-home** [comment]
Probier mal keine Leerzeichen zwischen new und Value.

**Comment by superbraz** [comment]
Hatte ich bereits probiert, habe es auch mit ChatGPT versucht, Syntax war wohl okay aber die Homebridge startete trotzdem nicht mit der angepassten Datei. Da fehlt mir einfach das Know-how. Falls hier also jemand behilflich sein kann!?

anbei mal ein LOG aus dem debug mode:
`[8/29/2024, 7:26:00 AM] [homebridge-homematic] This plugin generated a warning from the characteristic 'Position State': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[8/29/2024, 7:26:00 AM] [homebridge-homematic] Error: 
    at PositionState.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at PositionState.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2908:14)
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2493:24
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:71:13
    at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:410:13
    at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:597:9
    at /homebridge/node_modules/homebridge-homematic/index.js:654:9
    at /homebridge/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:66:9
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Core] rega result for HmIP-RF.00111XXXXX:3.LEVEL is 0.000000
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Cache] write 0.000000 for HmIP-RF.00111XXXXX:3.LEVEL
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] got value for HmIP-RF.00111XXXXX:3.LEVEL (Value:0.000000)
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] Convert 0 for 3.LEVEL is 0
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] will cache 0 for HmIP-RF.00111XXXXX:3.LEVEL
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] cache HmIP-RF.00111XXXXX:3.LEVEL (0)
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Cache] write 0 for HmIP-RF.00111XXXXX:3.LEVEL
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] run callback with 0
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] transformDatapoint 3.LEVEL
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Cache] write 0 for HmIP-RF.00111XXXXX:3.LEVEL
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Core] rega result for HmIP-RF.00111XXXXX:1.STATE is 0
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Cache] write 0 for HmIP-RF.00111XXXXX:1.STATE
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [GDS] get close value result is 0
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [GDS] values match close state
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] transformDatapoint STATE
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] cache .STATE (0)
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] datapointEvent STATE with 0 channel HmIP-RF.00111XXXXX:1
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [GDS] garage event CH:HmIP-RF.00111XXXXX:1|DP:STATE|NV:0|TCS:false
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [GDS] One Sensor Mode Close is 0
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [GDS] is sensor Close Event
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] Check 0 (string) will match StateSensorClose 0 (number) - true
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [GDS] Close sensor hm value is 0 set targetDoorState 1
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] got value for Hoflicht_kurz.STATE (Value:false)
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] Format is:bool
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] Convert false for STATE is 0
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] will cache 0 for Hoflicht_kurz.STATE
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] cache Hoflicht_kurz.STATE (0)
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] run callback with 0
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Core] rega result for HmIP-RF.00111XXXXX:4.DIRECTION is 
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Cache] write  for HmIP-RF.00111XXXXX:4.DIRECTION
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] got value for HmIP-RF.00111XXXXX:4.DIRECTION (Value:)
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] Convert  for DIRECTION is 
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] will cache  for HmIP-RF.00111XXXXX:4.DIRECTION
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] cache HmIP-RF.00111XXXXX:4.DIRECTION ()
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Cache] write  for HmIP-RF.00111XXXXX:4.DIRECTION
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] run callback with 
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Generic] transformDatapoint DIRECTION
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Cache] write  for HmIP-RF.00111XXXXX:4.DIRECTION
[8/29/2024, 7:26:00 AM] [homebridge-homematic] This plugin generated a warning from the characteristic 'Position State': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[8/29/2024, 7:26:00 AM] [homebridge-homematic] Error: 
    at PositionState.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at PositionState.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2908:14)
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2493:24
    at /homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:15:18
    at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitBlindServiceIP.js:71:13
    at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:410:13
    at /homebridge/node_modules/homebridge-homematic/ChannelServices/HomeKitGenericService.js:597:9
    at /homebridge/node_modules/homebridge-homematic/index.js:654:9
    at /homebridge/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:66:9
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:42:9)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [RPC] event for HmIP-RF.CENTRAL:0.PONG with value ioBroker:hm-rpc.0:25cXXXXX45919df106XXXX683c22e2e7
[8/29/2024, 7:26:00 AM] [HomeMatic CCU3] [Cache] write ioBroker:hm-rpc.0:25cXXXXX45919df106XXXX683c22e2e7 for HmIP-RF.CENTRAL:0.PONG
[8/29/2024, 7:26:02 AM] [CameraUI] Garage Cam: Setting up camera, please be patient...`

**Comment by superbraz** [comment]
niemand eine Idee?

**Comment by YogieAnamCara** [comment]
Wird das Plugin überhaupt noch gepflegt? Selbst das Schwester-Plugin das man direkt auf der CCU installieren kann, ist anscheinend nicht mehr in Entwicklung!?
