### ISSUE TITLE
ProgrammableSwitchEvent.Characteristic.characteristicWarning

### ISSUE THREAD

**Issue by Basti2506** [thkl/homebridge-homematic#687]
**Describe the bug**

Hallo Thomas,

beim Drücken des virtuellen Schalters der die Aktualisierung meiner Variablen in Homekit anstoßen soll, wird eine Warnung bzw. ein Error im Log der Homebridge ausgegeben. Die Variablen werden nicht aktualisiert. Details dazu siehe im Log unten.

Meine Konfiguration: 
- Homebridge v1.3.4 auf QNAP NAS im Docker Container. 
- Homebridge Homematic v0.2.226. 
- CCU3 mit SW 3.59.6

Meine verwendeten Variablen heißen SwitchGarage & SwitchRollooeffnen. Diese können die Werte 1 oder 0 annehmen und werden über "variables": [] als Switch in Homebridge bzw. Homekit eingebunden. 
Die Werte der Variablen werden entweder manuell in Homekit durch betätigen des jeweiligen Switchs oder durch Programme in der CCU geändert. Dabei soll das Event "variable_update_trigger_channel" die Aktualisierung der Variablen in Homekit anstoßen, wenn diese durch ein Programm auf der CCU geändert wurden. Dafür habe ich ein Programm auf der CCU erstellt, welches den Virtuellen Button HM-RCV-50 BidCoS-RF:50 "kurz" betätigt, wenn sich der Wert einer Variablen ändert.
Den Eintrag zum Event habe ich in der config.json ergänzt (siehe unten).

**Which Homematic Device or Service the bug is about**
variable_update_trigger_channel
variables": [] 

**To Reproduce**
Immer wenn der Virtuelle Schalter durch Änderung der Variablen in der HomeMatic CCU gedrückt wird, tritt der Fehler auf. 

**Actual behaviour**
Variablen werden in Homebridge bzw. Homekit nicht aktualisiert.

**Expected behavior**
Variablen sollen bei Änderung in der CCU durch das Event aktualisiert werden.

**LogFile**

[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[RPC] <- system.multicall on BidCos-RF. (null)[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[RPC] event for BidCos-RF.OEQ0670681:1.TEMPERATURE with value 25.2[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Cache] write 25.2 for BidCos-RF.OEQ0670681:1.TEMPERATURE[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[RPC] Accessory (Wohnzimmer Klima) found by channeladress (BidCos-RF.OEQ0670681:1) -> Send Event with value 25.2[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] transformDatapoint TEMPERATURE[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] cache BidCos-RF.OEQ0670681:1.TEMPERATURE (25.2)[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Cache] write 25.2 for BidCos-RF.OEQ0670681:1.TEMPERATURE[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] datapointEvent 1.TEMPERATURE with 25.2 channel BidCos-RF.OEQ0670681:1[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] isDataPointEvent check 1.TEMPERATURE vs 1.TEMPERATURE for channel 1[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] isDataPointEvent check 1.TEMPERATURE vs 1.HUMIDITY for channel 1[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] Saving log data for Wohnzimmer Klima: {"temp":25.2,"pressure":0,"humidity":52,"time":1631112048}[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90mFirst entry Wohnzimmer Klima: 0[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90mLast entry Wohnzimmer Klima: 37[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90mUsed memory Wohnzimmer Klima: 37[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m116 Wohnzimmer Klima: 0d1d010000000000e3e5e72603 0102 0202 03023800c00f00000000000000000101[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m** Fakegato-storage write FS file: /homebridge/TS251Plus_BidCos-RF.OEQ0670681:1_persist.json "firstEntry":0,"lastEntry":55,"usedMemory":55,"refTime":652731875,"initialTime":[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[RPC] event for BidCos-RF.OEQ0670681:1.HUMIDITY with value 52[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Cache] write 52 for BidCos-RF.OEQ0670681:1.HUMIDITY[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[RPC] Accessory (Wohnzimmer Klima) found by channeladress (BidCos-RF.OEQ0670681:1) -> Send Event with value 52[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] transformDatapoint HUMIDITY[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] cache BidCos-RF.OEQ0670681:1.HUMIDITY (52)[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Cache] write 52 for BidCos-RF.OEQ0670681:1.HUMIDITY[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] datapointEvent 1.HUMIDITY with 52 channel BidCos-RF.OEQ0670681:1[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] isDataPointEvent check 1.HUMIDITY vs 1.TEMPERATURE for channel 1[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] isDataPointEvent check 1.HUMIDITY vs 1.HUMIDITY for channel 1[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[RPC] <- system.multicall on BidCos-RF. (null)[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[RPC] event for BidCos-RF.BidCoS-RF:50.PRESS_SHORT with value true[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Cache] write true for BidCos-RF.BidCoS-RF:50.PRESS_SHORT[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[RPC] Accessory (HM RCV 50 BidCoS RF 50) found by channeladress (BidCos-RF.BidCoS-RF:50) -> Send Event with value true[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] transformDatapoint PRESS_SHORT[39m
[37m[9/8/2021, 4:40:48 PM] [39m[90m[36m[homebridge-homematic][39m[90m Characteristic 'Programmable Switch Event': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.[39m
[37m[9/8/2021, 4:40:48 PM] [39m[90m[36m[homebridge-homematic][39m[90m Error: [39m
[90m    at ProgrammableSwitchEvent.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)[39m
[90m    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1663:22[39m
[90m    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18[39m
[90m    at ProgrammableSwitchEvent.<anonymous> (/homebridge/node_modules/homebridge-homematic/ChannelServices/HomeMaticHomeKitVariableUpdaterService.js:21:21)[39m
[90m    at ProgrammableSwitchEvent.emit (events.js:400:28)[39m
[90m    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16[39m
[90m    at new Promise (<anonymous>)[39m
[90m    at ProgrammableSwitchEvent.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)[39m
[90m    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)[39m
[90m    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90mVariable update trigger was pressed (true)[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] transformDatapoint [39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90mUpdate variable SwitchGarage with false[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] transformDatapoint STATE[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] cache SwitchGarage.STATE (false)[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] datapointEvent STATE with false channel SwitchGarage[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90mUpdate variable SwitchRollooeffnen with false[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] transformDatapoint STATE[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] cache SwitchRollooeffnen.STATE (false)[39m
[37m[9/8/2021, 4:40:48 PM] [39m[36m[HomeMatic CCU][39m [90m[Generic] datapointEvent STATE with false channel SwitchRollooeffnen[39m

**config.json**

{
    "name": "HomeMatic CCU",
    "ccu_ip": "xxx.xxx.xxx.xx",
    "subsection": "Homekit",
    "enable_hmip": true,
    "enable_wired": false,
    "ios10": true,
    "platform": "HomeMatic",
    "variables": [
        "SwitchGarage",
        "SwitchRollooeffnen"
    ],
    "variable_update_trigger_channel": "HM-RCV-50 BidCoS-RF:50"
}

Würde mich sehr freuen, wenn du dir das mal ansehen könntest, was bei mir verkehrt läuft.

VG

Basti

**Comment by padman74** [comment]
Hello,
I have exactly the same problem after installation of new npm environment. 
What did you do to fix it? I also tried to downgrade to older homebridge-homebridge version, but still same issue.

Thank you and regards
Volker
