### ISSUE TITLE
Bekomme leider immer eine Error Meldung

### ISSUE THREAD

**Issue by Nyrmo** [thkl/homebridge-homematic#71]
Hallo,
ich habe Probleme Kontakt mit der CCU2 aufzubauen.
Als Fehlermeldung bekommen ich immer:
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at /usr/lib/node_modules/homebridge-homematic/index.js:299:9
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:41:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Leider kann ich damit nichts anfangen und im Netzt habe ich auch nichts dazu gefunden.

Unter platforms habe ich folgendes hinterlegt:
 {
           "platform": "HomeMatic",
           "name": "HomeMatic CCU",
           "ccu_ip": "192.168.100.85",
           "filter_device":[],
           "filter_channel":[],
           "outlets":[],
           "doors":[],
           "programs":[],
           "subsection":"Homekit"
		   }

und an Ports habe ich geöffnet: 2000, 2001, 2002, 5353, 9090, 9091, 9092 und 51826

Bin allmählich am verzweifeln. Habe leider nicht so viel Erfahrung damit und an dieser Stelle komme ich einfach nicht weiter.
Würde mich über jede Hilfe freuen!

**Comment by dkrizic** [comment]
Starte mal die CCU2 durch und stell sicher, dass nicht noch ein homebridge-Prozess läuft.

**Comment by Nyrmo** [comment]
Vielen Dank für deine Antwort! Funktioniert leider immer noch nicht.
Im Moment läuft das ganze auch auf meinem Docker for Windows auf meinem Server. Eventuell könnte es ja auch daran liegen, dass da irgendwas noch nicht ausgereift ist (Firewall ist test halber komplett deaktiviert).
Werde in den nächsten Tagen mal das ganze auf einem raspberry pi 2 aufsetzen. Vielleicht habe ich da mehr glück.
Fogelnd habe ich einfach mal meinen kompletten Container Log hinterlegt. Vielleicht fällt dir zufällig ja noch etwas anderes auf.
Aber auf jeden Fall schon mal vielen vielen Dank, dass dir überhaupt die Zeit nimmst.


Process 11 died: No such process; trying to remove PID file. (/var/run/avahi-daemon//pid)
/root/install_plugins.sh: line 7: /root/.homebridge/pluginsInstallList: No such file or directory
mv: cannot stat ‘/root/.homebridge/pluginsInstallList’: No such file or directory
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[11/30/2016, 11:10:50 AM] Loaded plugin: homebridge-homematic
[11/30/2016, 11:10:50 AM] Registering platform 'homebridge-homematic.HomeMatic'
[11/30/2016, 11:10:50 AM] ---
[11/30/2016, 11:10:50 AM] Loaded config.json with 0 accessories and 1 platforms.
[11/30/2016, 11:10:50 AM] ---
[11/30/2016, 11:10:51 AM] Loading 1 platforms...
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] Initializing HomeMatic platform...
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] Homematic Plugin Version 0.0.55
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] init RPC
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] Local IP: 172.17.0.2
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
[11/30/2016, 11:10:51 AM] [HomeMatic CCU] Fetching Homematic devices...
[11/30/2016, 11:10:51 AM] Loading 0 accessories...
[11/30/2016, 11:10:59 AM] [HomeMatic CCU] NPM 0.0.55 vs Local 0.0.55
[11/30/2016, 11:11:51 AM] [HomeMatic CCU] timeout while executing rega script
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[11/30/2016, 11:11:51 AM] Homebridge is running on port 51826.
[11/30/2016, 11:11:51 AM] [HomeMatic CCU] Number of mapped devices : 0
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at /usr/lib/node_modules/homebridge-homematic/index.js:299:9
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homematic/HomeMaticRegaRequest.js:41:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by dkrizic** [comment]
Kannst Du das Ding mal ohne Docker laufen lassen, testweise? HBHM teilt der CCU einen IP-Adresse für Rückantworten mit, und zwar Local IP: 172.17.0.2, kann die CCU diese überhaupt erreichen? Du müsstest noch 9090:9090 im Docker mappen ("XML-RPC server for interface BidCos-RF.is listening on port 9090").

**Comment by Nyrmo** [comment]
Ohne Docker geht im Moment nicht, da das ganze in einem Docker Container läuft.
Die IP Adresse ist mir auch schon aufgefallen. Keine Ahnung, wieso er die nennt. Die CCU hat 192.168.100.85 und der Server, auf dem die HB läuft, hat 192.168.100.100. Das Docker interne Virtuelle Netz hat 10.0.75.0.
Ein 172er bereich ist nirgends eingestellt.
Den Port 9090 habe ich schon durchgeschleift.

**Comment by AlexanderSchaaf** [comment]
Ich hatte auch diese Fehlermeldung: "This callback function has already been called by someone else",

Habe das in Docker nur zum Laufen bekommen, wenn ich dem Container das host-Netzwerk gebe (nennt man das so?), also ohne Bridge.

**Comment by Nyrmo** [comment]
Vielen Dank für den Tip! Jetzt schaut es schon mal anders aus! Aber funktionieren tut es noch nicht. Bin aber froh, dass es Fortschritte gibt!
Auf der CCU habe ich zum testen aktuell einen Schalter im entsprechenden Gewerk hinterlegt.
Aktuell ist das dabei raus gekommen:

Process 11 died: No such process; trying to remove PID file. (/var/run/avahi-daemon//pid)
/root/install_plugins.sh: line 7: /root/.homebridge/pluginsInstallList: No such file or directory
mv: cannot stat ‘/root/.homebridge/pluginsInstallList’: No such file or directory
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[11/30/2016, 1:23:17 PM] Loaded plugin: homebridge-homematic
[11/30/2016, 1:23:17 PM] Registering platform 'homebridge-homematic.HomeMatic'
[11/30/2016, 1:23:17 PM] ---
[11/30/2016, 1:23:17 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/30/2016, 1:23:17 PM] ---
[11/30/2016, 1:23:17 PM] Loading 1 platforms...
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] Initializing HomeMatic platform...
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] Homematic Plugin Version 0.0.55
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] init RPC
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] Local IP: 172.17.0.2
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
[11/30/2016, 1:23:17 PM] [HomeMatic CCU] Fetching Homematic devices...
[11/30/2016, 1:23:18 PM] Loading 0 accessories...
[11/30/2016, 1:23:21 PM] [HomeMatic CCU] Error Error: connect EHOSTUNREACH 192.168.100.85:8181while executing rega script string sDeviceId;string sChannelId;boolean df = true;Write('{"devices":[');foreach(sDeviceId, root.Devices().EnumIDs()){object oDevice = dom.GetObject(sDeviceId);if(oDevice){var oInterface = dom.GetObject(oDevice.Interface());if(df) {df = false;} else { Write(',');}Write('{');Write('"id": "' # sDeviceId # '",');Write('"name": "' # oDevice.Name() # '",');Write('"address": "' # oDevice.Address() # '",');Write('"type": "' # oDevice.HssType() # '",');Write('"channels": [');boolean bcf = true;foreach(sChannelId, oDevice.Channels().EnumIDs()){object oChannel = dom.GetObject(sChannelId);if(bcf) {bcf = false;} else {Write(',');}Write('{');Write('"cId": ' # sChannelId # ',');Write('"name": "' # oChannel.Name() # '",');if(oInterface){Write('"address": "' # oInterface.Name() #'.' # oChannel.Address() # '",');}Write('"type": "' # oChannel.HssType() # '"');Write('}');}Write(']}');}}Write(']');var s = dom.GetObject("Homekit");string cid;boolean sdf = true;if (s) {Write(',"subsection":[');foreach(cid, s.EnumUsedIDs()){  if(sdf) {sdf = false;} else { Write(',');}Write(cid);}Write(']');}Write('}');
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[11/30/2016, 1:23:21 PM] Homebridge is running on port 51826.
[11/30/2016, 1:23:21 PM] [HomeMatic CCU] Number of mapped devices : 0
[11/30/2016, 1:23:25 PM] [HomeMatic CCU] NPM 0.0.55 vs Local 0.0.55

**Comment by dkrizic** [comment]
Da steht

[11/30/2016, 1:23:21 PM] [HomeMatic CCU] Error Error: connect EHOSTUNREACH 192.168.100.85:8181

drin, was schlicht bedeutet, dass er die IP 192.168.100.85, Port 8181 nicht erreichen kann.

**Comment by Nyrmo** [comment]
So nur kurz zur Info;
das Problem liegt bei der Docker Bridge. Bekomme es aber nicht bei Docker for Windows hin, die Bridge raus zu bekommen. Also leider doch mit nem PI aufsetzen. 
Scheiße :-(

**Comment by Spybyte** [comment]
Hi,

funktioniert die Anbindung bei dir mit dem PI im Docker Bridge Modus? Ich habe das Ganze auf dem PI im Host Mode laufen. Evtl. ist das ja auch eine Möglichkeit für dein Docker Windows Problem...

**Comment by Nyrmo** [comment]
Habe mich noch nicht weiter damit befassen können. Ab nächste Woche habe ich Urlaub. Dann wollte ich mal alles auf nen PI umstellen.

**Comment by thkl** [comment]
Noch aktuell ?

**Comment by Nyrmo** [comment]
Habe jetzt über die Feiertage noch nicht wieder rum probiert. Muss mich aber mal damit befassen.
