### ISSUE TITLE
Crash seit 0.060 Update

### ISSUE THREAD

**Issue by nobiman** [thkl/homebridge-homematic#83]
Seit o.g Update crasht die Bridge beim ändern eines Wertes bzw. schalten eines Aktors:

log:
`[2016-12-22 19:53:36] [HomeMatic CCU] Number of mapped devices : 47
[2016-12-22 19:53:37] Homebridge is running on port 51826.
[2016-12-22 19:53:37] [HomeMatic CCU] NPM 0.0.60 vs Local 0.0.60
[2016-12-22 19:53:51] [Denon Wohnzimmer] current power state is: ON
[2016-12-22 19:53:51] [Denon Wohnzimmer] current volume is: 36
[2016-12-22 19:53:52] [Stereo Volume] Receiver MainZone Volume power state is 1
[2016-12-22 19:53:52] [Stereo Volume] Get receiver volume 36 

[2016-12-22 19:54:09] [HomeMatic CCU] (Rpc) Send false to Datapoint STATE at BidCos-RF.IEQ0073534:1`

(Letzte Zeile zeigt den Schaltvorgang)

err:
`/usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:209
	 this.log.debug("RPC setValue (%s %s) Response %s Errors: %s",channel, datapoint, JSON.stringify(value),error);
	     ^

TypeError: Cannot read property 'log' of undefined
    at /usr/lib/node_modules/homebridge-homematic/HomeMaticRPC.js:209:7
    at Deserializer.callback (/usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:42:7)
    at Deserializer.onDone (/usr/lib/node_modules/homebridge-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:92:12)
    at emitNone (events.js:86:13)
    at SAXStream.emit (events.js:185:7)
    at Object.SAXStream._parser.onend (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:363:3)
    at Object.end (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/lib/node_modules/homebridge-homematic/node_modules/sax/lib/sax.js:209:16)
`
Edit: Schaltaktion wurde über Eve bzw. Home App durchgeführt.
Edit#2: Downgrade auf 0.0.59: Alles löppt wieder ;)

**Comment by thkl** [comment]
ach f*gg .. ich fix das gleich ...

**Comment by nobiman** [comment]
Löppt!
Superklasse!
Danke!
