### ISSUE TITLE
Homebridge startet nicht mit HM Plugin

### ISSUE THREAD

**Issue by iHorstD** [thkl/homebridge-homematic#94]
Hi,
leider startet die HB nicht mit dem HM Plugin. Ohne läuft alles mit der Fritzbox und den Lightify Lampen. Ist meine Config Datei falsch? Wo kann ich nachsehen (Logs)?
Gruß Horst

Konfig:
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxxx",
        "port": 51826,
        "pin": "031-45-154"
    },

    "accessories": [
    ],

    "platforms": [

{
      "platform": "Fritz!Box",
      "name": "FritzBox",
      "username": "xxx",
      "password": "xxx",
      "url": "http://192.168.178.22",
      "interval": 60,
      "debug": false
    },
{
    "platform": "Lightify API",
    "username": "xxxx",
    "password": "xxx",
    "serialNumber": "xxxx",

    "apiURL": "https://eu.lightify-api.org/lightify/services/",
    "fadeTime": 3
},
{
„platform“: „HomeMatic“,
„name“: „HomeMatic CCU2“,
„ccu_ip“: „192.168.178.30“,
„filter_device“: [],
„filter_channel“: [],
„outlets“: [],
„doors“: [],
„programs“: [],
„accessories“: [],
„subsection“: „HomeKit“
}
    ]
}

Fehler:
[2017-02-01 00:03:02] ---
[2017-02-01 00:03:02] There was a problem reading your config.json file.
[2017-02-01 00:03:02] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2017-02-01 00:03:02] 
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token „ in JSON at position 638
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by jp112sdl** [comment]
Die **Anführungszeichen** in der Homematic-Sektion sind nicht korrekt.
**"** muss es sein. Bei dir sind da aber überall „ und “
Passiert manchmal, wenn man Text von einer Webseite 1:1 kopiert und übernimmt ;) 

Hier also die korrigierte Version:

{
"bridge": {
"name": "Homebridge",
"username": "xxxx",
"port": 51826,
"pin": "031-45-154"
},

"accessories": [
],

"platforms": [
{
"platform": "Fritz!Box",
"name": "FritzBox",
"username": "xxx",
"password": "xxx",
"url": "http://192.168.178.22",
"interval": 60,
"debug": false
},
{
"platform": "Lightify API",
"username": "xxxx",
"password": "xxx",
"serialNumber": "xxxx",

"apiURL": "https://eu.lightify-api.org/lightify/services/",
"fadeTime": 3
},
{
"platform": "HomeMatic",
"name": "HomeMatic CCU2",
"ccu_ip": "192.168.178.30",
"filter_device": [],
"filter_channel": [],
"outlets": [],
"doors": [],
"programs": [],
"accessories": [],
"subsection": "HomeKit"
}
]
}

**Comment by iHorstD** [comment]
Ohhhh Mannnn... das hätte ich auch selber finden können. Probiere das heute Abend direkt aus.
Danke und Gruß

**Comment by iHorstD** [comment]
Habe es probiert... jetzt kommt folgendes:
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:372:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-fritz/index.js:125:25
    at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:666:14)

**Comment by thkl** [comment]
homebridge läuft schon. Vor dem Neustart beenden

**Comment by jp112sdl** [comment]
'Error: listen EADDRINUSE'
heißt, dass die IP/das Interface, an das sich homebridge binden will, schon belegt ist. 
Meist ist das der Fall, wenn schon ein Prozess läuft, während man einen weiteren starten möchte.

**Comment by iHorstD** [comment]
Hallo, danke. Geht jetzt. Nun habe ich zu viele Geräte drin. Dachte, dass nur die zu sehen sind, die im Gewerk HomeKit zugeordnet sind. Aber auch alle Fernbedienungskanäle usw. sind drin. Muss mal schauen was ich da falsch in der Config habe.

Gruß

**Comment by jp112sdl** [comment]
Die Config ist in Ordnung und es wird auch nur das Gewerk HomeKit angezeigt. 
Prüfe noch mal das Gewerk der CCU.

**Comment by iHorstD** [comment]
Hi, habe es gefunden. HomeKit muss bei mit Homekit heißen. Am Mac schlägt die Korrektur schnell mal zu.

Danke

**Comment by thkl** [comment]
👍
